-- ============================================================================
-- 불라방 교재주문: 강사가 입금 계좌와 교재를 직접 등록한다 (2026-09-21 Alan —
--   "교재비를 받는 계좌번호와 교재 과목 등록은 강사가 직접 할 수 있도록 해보자")
--
--   첫토익 문서 04 의 "1인 강사용 최소 구성" 을 따랐다:
--   * **카탈로그·계좌를 DB 로** — 가격·계좌가 바뀌어도 배포가 필요 없다. 화면은 /admin/textbook-orders/setup (강사·관리자).
--   * **주문은 함수 하나로** (public.create_textbook_order) — 학생이 표에 직접 넣지 못한다.
--     품목·금액·입금 계좌는 **서버가 계산해 주문에 박아 둔다** (첫토익은 앱이 계산한 금액을 그대로 넣었다 — 공통 원칙 2).
--   * **한 달에 한 건** — (학생, 기수) 로 막는다. 주5일 학생이 월수금·화목금 반마다 두 번 주문하던 틈도 이것으로 닫힌다.
--   * **예비등록생도 주문한다** — 개강 전에 등업한 불라방 학생이 개강 전에 교재를 받아야 한다.
--   * 이 사이트는 결제를 **처리하지 않는다** — 계좌와 금액을 안내하고, 입금자명을 받고, 강사가 통장과 대조해 "입금 확인" 을 누른다.
--
--   계좌·교재 목록은 강사·관리자·조교와 **불라방 배정이 있는 학생만** 읽는다 (첫토익 12 — 계좌를 전체 공개로 열었던 사고).
-- ============================================================================

-- ─── 1. 입금 계좌 ──────────────────────────────────────────────────────────
create table if not exists public.textbook_accounts (
  id          bigint generated by default as identity primary key,
  bank_name   text not null check (char_length(bank_name) between 1 and 30),
  account_no  text not null check (char_length(account_no) between 4 and 40),
  holder      text not null check (char_length(holder) between 1 and 30),
  label       text check (label is null or char_length(label) <= 40),   -- 예: "LC 교재비" — 계좌가 둘 이상일 때 가른다
  active      boolean not null default true,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.textbook_accounts is '교재비 입금 계좌 (강사가 등록). 학생 주문 화면에 금액과 함께 보인다';

-- ─── 2. 교재 ──────────────────────────────────────────────────────────────
create table if not exists public.textbook_items (
  id          bigint generated by default as identity primary key,
  name        text not null check (char_length(name) between 1 and 60),
  level       int references public.lc_levels (level),        -- null = 모든 레벨. 학생은 자기 레벨 교재만 본다
  price       int not null check (price between 0 and 1000000),
  account_id  bigint references public.textbook_accounts (id) on delete set null,  -- null = 기본 계좌
  note        text check (note is null or char_length(note) <= 200),
  active      boolean not null default true,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.textbook_items is '불라방 교재 (강사가 등록). level 이 비면 모든 레벨. 주문에는 이름·가격을 그 때의 값으로 박아 둔다';

-- ─── 3. 배송비·기본 계좌·안내 (한 줄) ──────────────────────────────────────
create table if not exists public.textbook_settings (
  id                 boolean primary key default true check (id),
  shipping_fee       int not null default 0 check (shipping_fee between 0 and 100000),
  default_account_id bigint references public.textbook_accounts (id) on delete set null,  -- 배송비·계좌를 안 고른 교재는 여기로
  notice             text check (notice is null or char_length(notice) <= 300),
  updated_at         timestamptz not null default now()
);

insert into public.textbook_settings (id) values (true) on conflict (id) do nothing;

-- ─── 4. 주문에 품목·금액·입금 정보를 박아 둔다 ────────────────────────────
alter table public.textbook_orders
  add column if not exists term_id        bigint references public.terms (id),
  add column if not exists items          jsonb not null default '[]'::jsonb,   -- [{id, name, price, account_id}] 주문한 때의 값
  add column if not exists items_total    int not null default 0,
  add column if not exists shipping_fee   int not null default 0,
  add column if not exists total_amount   int not null default 0,
  add column if not exists depositor_name text check (depositor_name is null or char_length(depositor_name) <= 30),
  add column if not exists pay_to         jsonb not null default '[]'::jsonb;   -- [{account_id, bank_name, account_no, holder, label, amount}]

comment on column public.textbook_orders.pay_to is '입금 안내 (주문한 때의 계좌·금액). 계좌를 바꿔도 지난 주문의 안내는 그대로다';

update public.textbook_orders o
   set term_id = s.term_id
  from public.class_sections s
 where s.id = o.section_id and o.term_id is null;

-- 한 달에 한 건 (취소한 것은 빼고)
create unique index if not exists textbook_orders_one_per_term
  on public.textbook_orders (user_id, term_id)
  where status <> 'cancelled' and term_id is not null;

-- ─── 5. 누가 읽고 쓰나 ────────────────────────────────────────────────────
-- 불라방 배정이 살아 있는 학생인가 (예비등록생 포함, 종강 전)
create or replace function private.has_live_enrollment()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.enrollments e
      join public.enrollment_orders o on o.id = e.order_id
      join public.class_sections s on s.id = e.section_id
     where e.student_id = (select auth.uid())
       and e.mode = 'live'
       and e.status = 'active'
       and o.status in ('preliminary', 'active')
       and private.today_kst() <= s.closes_at
  )
$$;

-- 정책 안에서 부르므로 로그인 사용자가 실행할 수 있어야 한다 (자기에게 불라방 배정이 있는지만 알려 준다)
revoke all on function private.has_live_enrollment() from public, anon;
grant execute on function private.has_live_enrollment() to authenticated, service_role;

grant select, insert, update, delete on public.textbook_accounts, public.textbook_items to authenticated;
grant select, update on public.textbook_settings to authenticated;
grant all on public.textbook_accounts, public.textbook_items, public.textbook_settings to service_role;

alter table public.textbook_accounts enable row level security;
alter table public.textbook_items    enable row level security;
alter table public.textbook_settings enable row level security;

create policy "textbook_accounts: 스태프·조교·불라방 학생 조회" on public.textbook_accounts
  for select to authenticated
  using ((select private.is_crew()) or (active and (select private.has_live_enrollment())));
create policy "textbook_accounts: 스태프 등록" on public.textbook_accounts
  for insert to authenticated with check ((select private.is_staff()));
create policy "textbook_accounts: 스태프 수정" on public.textbook_accounts
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "textbook_accounts: 스태프 삭제" on public.textbook_accounts
  for delete to authenticated using ((select private.is_staff()));

create policy "textbook_items: 스태프·조교·불라방 학생 조회" on public.textbook_items
  for select to authenticated
  using ((select private.is_crew()) or (active and (select private.has_live_enrollment())));
create policy "textbook_items: 스태프 등록" on public.textbook_items
  for insert to authenticated with check ((select private.is_staff()));
create policy "textbook_items: 스태프 수정" on public.textbook_items
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "textbook_items: 스태프 삭제" on public.textbook_items
  for delete to authenticated using ((select private.is_staff()));

create policy "textbook_settings: 스태프·조교·불라방 학생 조회" on public.textbook_settings
  for select to authenticated
  using ((select private.is_crew()) or (select private.has_live_enrollment()));
create policy "textbook_settings: 스태프 수정" on public.textbook_settings
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));

-- 학생은 주문 표에 직접 넣거나 고치지 못한다 — 품목·금액을 바꿔 넣는 길을 막는다. 넣기·취소는 아래 함수로만.
-- 강사·조교의 처리(상태·송장)는 그대로 세션으로 한다
drop policy if exists "textbook_orders: 불라방 수강생 신청" on public.textbook_orders;
drop policy if exists "textbook_orders: 본인 취소·스태프·조교 처리" on public.textbook_orders;
revoke insert on public.textbook_orders from authenticated;

create policy "textbook_orders: 스태프·조교 처리" on public.textbook_orders
  for update to authenticated
  using ((select private.is_crew()))
  with check ((select private.is_crew()));

-- ─── 6. 주문 넣기 — 품목·금액·계좌를 서버가 정한다 ─────────────────────────
create or replace function public.create_textbook_order(
  p_term_id        bigint,
  p_item_ids       bigint[],
  p_recipient      text,
  p_phone          text,
  p_postal_code    text,
  p_address        text,
  p_address_detail text,
  p_memo           text,
  p_depositor      text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid       uuid := (select auth.uid());
  v_section   bigint;
  v_levels    int[];
  v_items     jsonb;
  v_total     int;
  v_count     int;
  v_wanted    int;
  v_ship      int;
  v_default   bigint;
  v_pay       jsonb;
  v_phone     text := regexp_replace(coalesce(p_phone, ''), '\D', '', 'g');
  v_postal    text := nullif(regexp_replace(coalesce(p_postal_code, ''), '\D', '', 'g'), '');
  v_recipient text := btrim(coalesce(p_recipient, ''));
  v_address   text := btrim(coalesce(p_address, ''));
  v_detail    text := nullif(btrim(coalesce(p_address_detail, '')), '');
  v_memo      text := nullif(btrim(coalesce(p_memo, '')), '');
  v_depositor text := btrim(coalesce(p_depositor, ''));
  v_id        bigint;
begin
  if v_uid is null then
    raise exception 'login_required';
  end if;

  -- 그 달 불라방 배정 (예비등록생 포함, 종강 전). 대표 반은 월수금을 먼저 — 주5일이면 두 반 중 하나로 적는다
  select e.section_id
    into v_section
    from public.enrollments e
    join public.enrollment_orders o on o.id = e.order_id
    join public.class_sections s on s.id = e.section_id
   where e.student_id = v_uid
     and e.mode = 'live'
     and e.status = 'active'
     and o.status in ('preliminary', 'active')
     and s.term_id = p_term_id
     and private.today_kst() <= s.closes_at
   order by (s.track = 'mwf') desc, s.id
   limit 1;
  if v_section is null then
    raise exception 'not_eligible';
  end if;

  -- 내 레벨: 그 달 불라방 반의 강좌 레벨 + 속성반이 함께 듣는 레벨
  select coalesce(array_agg(distinct lv), '{}')
    into v_levels
    from (
      select unnest(c.includes_levels || c.target_score) as lv
        from public.enrollments e
        join public.enrollment_orders o on o.id = e.order_id
        join public.class_sections s on s.id = e.section_id
        join public.courses c on c.id = s.course_id
       where e.student_id = v_uid
         and e.mode = 'live'
         and e.status = 'active'
         and o.status in ('preliminary', 'active')
         and s.term_id = p_term_id
    ) x
   where lv is not null;

  -- 입력 검사 (화면이 먼저 보지만 믿지 않는다)
  if char_length(v_recipient) not between 2 and 30 then raise exception 'recipient'; end if;
  if v_phone !~ '^01\d{8,9}$' then raise exception 'phone'; end if;
  if char_length(v_address) not between 5 and 200 then raise exception 'address'; end if;
  if v_detail is not null and char_length(v_detail) > 100 then raise exception 'address'; end if;
  if v_postal is not null and char_length(v_postal) <> 5 then raise exception 'postal'; end if;
  if v_memo is not null and char_length(v_memo) > 200 then raise exception 'memo'; end if;
  if char_length(v_depositor) not between 1 and 30 then raise exception 'depositor'; end if;

  select s.shipping_fee, s.default_account_id into v_ship, v_default from public.textbook_settings s where s.id;
  -- 기본 계좌가 비었으면 쓰는 중인 첫 계좌
  if v_default is null or not exists (select 1 from public.textbook_accounts a where a.id = v_default and a.active) then
    select a.id into v_default from public.textbook_accounts a where a.active order by a.sort_order, a.id limit 1;
  end if;

  -- 고른 교재: 쓰는 중이고 내 레벨(또는 모든 레벨)인 것만. 하나라도 어긋나면 거절한다
  select count(distinct x) into v_wanted from unnest(coalesce(p_item_ids, '{}')) x;
  select coalesce(jsonb_agg(jsonb_build_object(
             'id', i.id, 'name', i.name, 'price', i.price,
             'account_id', case when a.active then i.account_id else v_default end)
           order by i.sort_order, i.id), '[]'::jsonb),
         coalesce(sum(i.price), 0),
         count(*)
    into v_items, v_total, v_count
    from public.textbook_items i
    left join public.textbook_accounts a on a.id = i.account_id
   where i.id = any (p_item_ids)
     and i.active
     and (i.level is null or i.level = any (v_levels));
  if v_wanted = 0 or v_count <> v_wanted then
    raise exception 'invalid_items';
  end if;
  v_ship := coalesce(v_ship, 0);

  -- 계좌마다 얼마: 교재는 제 계좌(없으면 기본 계좌)로, 배송비는 기본 계좌로
  with lines as (
    select coalesce((e->>'account_id')::bigint, v_default) as account_id, (e->>'price')::int as amount
      from jsonb_array_elements(v_items) e
    union all
    select v_default, v_ship where v_ship > 0
  ),
  sums as (
    select account_id, sum(amount)::int as amount from lines group by account_id having sum(amount) > 0
  )
  select coalesce(jsonb_agg(jsonb_build_object(
             'account_id', a.id, 'bank_name', a.bank_name, 'account_no', a.account_no,
             'holder', a.holder, 'label', a.label, 'amount', s.amount)
           order by a.sort_order, a.id), '[]'::jsonb)
    into v_pay
    from sums s
    left join public.textbook_accounts a on a.id = s.account_id;

  -- 낼 돈이 있는데 받을 계좌가 없으면 주문을 받지 않는다 (강사가 계좌부터 등록해야 한다)
  if v_total + v_ship > 0 and (v_default is null or exists (select 1 from jsonb_array_elements(v_pay) p where p->>'account_id' is null)) then
    raise exception 'no_account';
  end if;

  begin
    insert into public.textbook_orders (
      user_id, section_id, term_id, recipient_name, phone, postal_code, address, address_detail,
      quantity, memo, status, items, items_total, shipping_fee, total_amount, depositor_name, pay_to
    )
    values (
      v_uid, v_section, p_term_id, v_recipient, v_phone, v_postal, v_address, v_detail,
      least(greatest(v_count, 1), 5), v_memo, 'requested', v_items, v_total, v_ship, v_total + v_ship, v_depositor, v_pay
    )
    returning id into v_id;
  exception when unique_violation then
    raise exception 'duplicate';
  end;

  return v_id;
end;
$$;

comment on function public.create_textbook_order(bigint, bigint[], text, text, text, text, text, text, text) is
  '불라방 교재 주문. 품목·금액·입금 계좌를 서버가 정해 박아 둔다. 오류: not_eligible · invalid_items · no_account · duplicate · 입력 칸 이름';

-- 입금 확인 전에는 본인이 취소한다
create or replace function public.cancel_textbook_order(p_id bigint)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
begin
  update public.textbook_orders
     set status = 'cancelled', updated_at = now()
   where id = p_id
     and user_id = (select auth.uid())
     and status = 'requested';
  return found;
end;
$$;

revoke all on function public.create_textbook_order(bigint, bigint[], text, text, text, text, text, text, text) from public, anon;
revoke all on function public.cancel_textbook_order(bigint) from public, anon;
grant execute on function public.create_textbook_order(bigint, bigint[], text, text, text, text, text, text, text) to authenticated;
grant execute on function public.cancel_textbook_order(bigint) to authenticated;
