-- ============================================================================
-- 랜딩 수업시간표: 목표 점수반별 수업 시간 (2026-09-15 Alan 확정)
--
--  * 랜딩의 "아침·오전·오후·저녁" 고정 칸을 실제 시간표로 바꾼다.
--  * 매달 편성하는 반(class_sections)과는 별개인 대표 시간표다. 시간대는 코드에 두지 않고 여기서 읽는다.
--  * 화면은 레벨 순서(sort_order) → 시작 시각 순으로 보여준다. 수정은 행만 바꾸면 된다.
-- ============================================================================

create table public.timetable_levels (
  level       int primary key check (level between 10 and 990),   -- 650 | 750 | 850
  note        text,                                                 -- 반 전체에 붙는 안내 (예: 월수금반 현장, 화목금반 인강)
  sort_order  int not null default 0
);
comment on table public.timetable_levels is '랜딩 수업시간표의 목표 점수반 (650 · 750 · 850)';

create table public.timetable_slots (
  id          bigint generated by default as identity primary key,
  level       int not null references public.timetable_levels (level) on delete cascade,
  start_time  time not null,
  end_time    time not null check (end_time > start_time),
  unique (level, start_time)
);
comment on table public.timetable_slots is '랜딩 수업시간표의 반별 수업 시간';

insert into public.timetable_levels (level, note, sort_order) values
  (650, null, 1),
  (750, '월수금반 현장, 화목금반 인강', 2),
  (850, null, 3);

insert into public.timetable_slots (level, start_time, end_time) values
  (650, '10:00', '12:10'), (650, '18:30', '20:40'),
  (750, '10:00', '12:10'), (750, '18:30', '20:40'),
  (850, '12:30', '13:40'), (850, '13:50', '15:00');

-- ─── grant + RLS: 누구나 조회, 쓰기는 대시보드(service_role)에서만 ─────────────
grant all on public.timetable_levels, public.timetable_slots to service_role;
grant select on public.timetable_levels, public.timetable_slots to anon, authenticated;

alter table public.timetable_levels enable row level security;
alter table public.timetable_slots  enable row level security;

create policy "timetable_levels: 공개 조회" on public.timetable_levels
  for select to anon, authenticated using (true);
create policy "timetable_slots: 공개 조회" on public.timetable_slots
  for select to anon, authenticated using (true);
