-- ============================================================================
-- 네이버 예약 자동 확인 (2026-09-21 Alan — "네이버는 첫토익 설정과 똑같이해주면 좋겠어.
--   예약이 잡히면 강사에게 알림이 오고 동시에 대시보드에서 바로 보이도록")
--
--   첫토익 문서 03 과 같은 방식: 네이버 예약 **공개 페이지가 쓰는 조회(hourlySchedule)** 를 10분마다 한 번 불러
--   칸마다 예약 건수를 받고, 직전 기록과 비교해 늘면 접수 · 줄면 취소로 기록한다. 조회는 우리 API
--   (/api/cron/naver-sync) 가 하고, 비교·저장은 이 파일의 public.naver_apply_snapshot 한곳이 **한 트랜잭션으로** 한다.
--
--   * 이 조회는 예약자가 누구인지 주지 않는다 — 칸마다 건수와 정원뿐이다. 알림에도 날짜·시각만 간다.
--   * 처음 본 칸은 **기준선** 으로만 저장한다 — 첫 실행에 이미 잡혀 있던 예약이 알림 폭탄이 되지 않게 (5-3).
--     단 지난번에도 보던 범위 안에 새로 생긴 칸의 예약은 그 사이 연 칸에 바로 잡힌 것이라 접수로 본다.
--   * 취소가 한꺼번에 3건 이상이면 **한 번 보류** 하고, 다음 확인(10분 뒤)에도 똑같으면 그때 반영한다 (6.4-1).
--   * 범위 안인데 응답에서 사라진 칸은 지운다 — 닫힌 칸이 '예약 가능' 으로 남지 않게 (5-7).
--     예약이 있던 칸이 사라지면 'vanished' 로 남겨 확인을 부탁한다.
--   * 차단(403·429)을 받으면 한 시간 동안 부르지 않는다 (retry_after). 우회하지 않는다 (6.5).
--
--   예전의 "알림 원문 전달" 방식(naver_reservations · /api/naver-reservations)은 운영에서 한 건도 받지 못해
--   대시보드가 더는 읽지 않는다. 표와 주소는 지우지 않고 남겨 둔다 (CLAUDE.md 도메인 규칙 8).
-- ============================================================================

-- ─── 1. 칸 기록 (지금 상태) ───────────────────────────────────────────────
create table if not exists public.naver_booking_slots (
  slot_at       timestamptz primary key,          -- 칸 시작 시각
  booking_count int not null default 0 check (booking_count >= 0),
  stock         int not null default 0 check (stock >= 0),   -- 정원 (역전토익 강사상담은 2명, 2026-09-21 실측)
  is_sale_day   boolean not null default true,
  updated_at    timestamptz not null default now()
);

comment on table public.naver_booking_slots is
  '네이버 예약 "역전토익 강사상담" 칸마다 예약 건수 (10분마다 갱신). 하루 넘게 지난 칸은 지운다';

-- ─── 2. 변동 기록 (쌓기만 한다) ───────────────────────────────────────────
create table if not exists public.naver_booking_events (
  id          bigint generated by default as identity primary key,
  slot_at     timestamptz not null,
  kind        text not null check (kind in ('booked', 'cancelled', 'vanished')),
  prev_count  int not null,
  new_count   int not null,
  stock       int,
  created_at  timestamptz not null default now()   -- 알아챈 시각
);

create index if not exists naver_booking_events_created_idx on public.naver_booking_events (created_at desc);

comment on table public.naver_booking_events is
  '네이버 예약 변동: booked(접수) · cancelled(취소) · vanished(예약이 있던 칸이 사라짐 — 확인 필요)';

-- ─── 3. 수집 상태 (한 줄) ─────────────────────────────────────────────────
-- 크론 기록은 늘 '성공' 이라 믿을 수 없다 — 마지막 성공 시각을 대시보드에 보여 준다
create table if not exists public.naver_sync_status (
  id                   boolean primary key default true check (id),
  last_run_at          timestamptz,
  last_success_at      timestamptz,
  last_error           text,
  last_error_at        timestamptz,
  consecutive_failures int not null default 0,
  retry_after          timestamptz,        -- 이 시각 전에는 부르지 않는다 (차단을 받았을 때)
  held_signature       text,               -- 한꺼번에 취소가 여럿 보여 보류한 변동의 지문
  slots                int not null default 0,
  range_to             timestamptz          -- 마지막으로 본 범위의 끝
);

insert into public.naver_sync_status (id) values (true) on conflict (id) do nothing;

comment on table public.naver_sync_status is '네이버 예약 확인 상태 (한 줄). 대시보드의 "마지막 확인" 이 읽는다';

-- ─── 4. 권한: 스태프는 읽기만, 쓰기는 서버(service_role)만 ────────────────
grant all on public.naver_booking_slots, public.naver_booking_events, public.naver_sync_status to service_role;
grant select on public.naver_booking_slots, public.naver_booking_events, public.naver_sync_status to authenticated;

alter table public.naver_booking_slots  enable row level security;
alter table public.naver_booking_events enable row level security;
alter table public.naver_sync_status    enable row level security;

create policy "naver_booking_slots: 스태프 조회" on public.naver_booking_slots
  for select to authenticated using ((select private.is_staff()));
create policy "naver_booking_events: 스태프 조회" on public.naver_booking_events
  for select to authenticated using ((select private.is_staff()));
create policy "naver_sync_status: 스태프 조회" on public.naver_sync_status
  for select to authenticated using ((select private.is_staff()));

-- ─── 5. 받은 칸을 비교해 저장한다 (한 트랜잭션) ────────────────────────────
-- p_slots: [{ "slot_at": ISO, "booking_count": int, "stock": int, "is_sale_day": bool }] — API 가 모양을 검사한 뒤 넘긴다
-- 돌려주는 값: { first, held, slots, events: [{ slot_at, kind, prev, new, stock }] } — 알림은 API 가 이 events 로 보낸다
create or replace function public.naver_apply_snapshot(p_from timestamptz, p_to timestamptz, p_slots jsonb)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_first   boolean;
  v_prev_to timestamptz;
  v_held    text;
  v_events  jsonb;
  v_cancels int;
  v_sig     text;
  v_count   int;
begin
  if jsonb_typeof(p_slots) is distinct from 'array' then
    raise exception 'p_slots 는 배열이어야 해요';
  end if;

  -- 두 번이 겹쳐 돌면 같은 알림이 두 번 간다 — 한 번에 하나만 (6.4-5)
  perform pg_advisory_xact_lock(hashtext('naver_booking_sync'));

  -- "처음" 은 칸 표가 비었는지가 아니라 **성공한 적이 있는지** 로 본다 — 열린 칸이 하나도 없던 날 뒤에
  -- 칸이 다시 열려도 그 칸의 예약을 기준선으로 묻어 버리지 않게
  select s.range_to, s.held_signature, s.last_success_at is null
    into v_prev_to, v_held, v_first
    from public.naver_sync_status s
   where s.id;
  v_first := coalesce(v_first, true);

  with fresh as (
    select distinct on (x.slot_at) x.slot_at, x.booking_count, x.stock
      from jsonb_to_recordset(p_slots) as x(slot_at timestamptz, booking_count int, stock int)
     order by x.slot_at
  ),
  old as (
    select o.slot_at, o.booking_count
      from public.naver_booking_slots o
     where o.slot_at between p_from and p_to
  ),
  ev as (
    -- 늘거나 줄어든 칸
    select f.slot_at,
           case when f.booking_count > o.booking_count then 'booked' else 'cancelled' end as kind,
           o.booking_count as prev, f.booking_count as new, f.stock
      from fresh f
      join old o on o.slot_at = f.slot_at
     where f.booking_count <> o.booking_count
    union all
    -- 지난번에도 보던 범위 안에 새로 생긴 칸의 예약 = 그 사이 연 칸에 바로 잡힌 예약
    select f.slot_at, 'booked', 0, f.booking_count, f.stock
      from fresh f
     where f.booking_count > 0
       and v_prev_to is not null
       and f.slot_at <= v_prev_to
       and not exists (select 1 from old o where o.slot_at = f.slot_at)
    union all
    -- 예약이 있던 칸이 응답에서 사라졌다. 곧 시작할 칸은 네이버가 먼저 닫을 수 있어 한 시간 넘게 남은 칸만 본다
    select o.slot_at, 'vanished', o.booking_count, 0, null::int
      from old o
     where o.booking_count > 0
       and o.slot_at > now() + interval '1 hour'
       and not exists (select 1 from fresh f where f.slot_at = o.slot_at)
  )
  select coalesce(
           jsonb_agg(jsonb_build_object('slot_at', ev.slot_at, 'kind', ev.kind, 'prev', ev.prev, 'new', ev.new, 'stock', ev.stock)
                     order by ev.slot_at, ev.kind),
           '[]'::jsonb)
    into v_events
    from ev;

  -- 첫 실행은 기준선뿐이다
  if v_first then
    v_events := '[]'::jsonb;
  end if;

  -- 취소가 한꺼번에 3건 이상이면 한 번 보류한다. 다음 확인에도 같은 변동이면 그때 반영한다
  select count(*) into v_cancels
    from jsonb_array_elements(v_events) e
   where e->>'kind' in ('cancelled', 'vanished');
  if v_cancels >= 3 then
    v_sig := md5(v_events::text);
    if v_held is distinct from v_sig then
      update public.naver_sync_status
         set held_signature = v_sig, last_run_at = now()
       where id;
      return jsonb_build_object('first', false, 'held', true, 'slots', jsonb_array_length(p_slots), 'events', v_events);
    end if;
  end if;

  insert into public.naver_booking_events (slot_at, kind, prev_count, new_count, stock)
  select (e->>'slot_at')::timestamptz, e->>'kind', (e->>'prev')::int, (e->>'new')::int, (e->>'stock')::int
    from jsonb_array_elements(v_events) e;

  insert into public.naver_booking_slots (slot_at, booking_count, stock, is_sale_day, updated_at)
  select distinct on (x.slot_at) x.slot_at, x.booking_count, x.stock, coalesce(x.is_sale_day, true), now()
    from jsonb_to_recordset(p_slots) as x(slot_at timestamptz, booking_count int, stock int, is_sale_day boolean)
   order by x.slot_at
  on conflict (slot_at) do update
     set booking_count = excluded.booking_count,
         stock         = excluded.stock,
         is_sale_day   = excluded.is_sale_day,
         updated_at    = now();

  -- 범위 안인데 응답에 없는 칸 (닫힌 칸) · 하루 넘게 지난 칸은 지운다. 변동 기록은 남긴다
  delete from public.naver_booking_slots o
   where (o.slot_at between p_from and p_to
          and not exists (
            select 1 from jsonb_to_recordset(p_slots) as x(slot_at timestamptz) where x.slot_at = o.slot_at))
      or o.slot_at < now() - interval '1 day';

  select count(*) into v_count from public.naver_booking_slots;

  update public.naver_sync_status
     set last_run_at          = now(),
         last_success_at      = now(),
         last_error           = null,
         consecutive_failures = 0,
         retry_after          = null,
         held_signature       = null,
         slots                = v_count,
         range_to             = p_to
   where id;

  return jsonb_build_object('first', v_first, 'held', false, 'slots', v_count, 'events', v_events);
end;
$$;

comment on function public.naver_apply_snapshot(timestamptz, timestamptz, jsonb) is
  '네이버 예약 칸을 직전 기록과 비교해 변동을 남기고 저장한다 (한 트랜잭션). service_role 전용 — /api/cron/naver-sync 가 부른다';

-- 실패를 기록하고 몇 번째 연속 실패인지 돌려준다. p_retry_after 가 있으면 그때까지 부르지 않는다
create or replace function public.naver_sync_failed(p_error text, p_retry_after timestamptz default null)
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_n int;
begin
  update public.naver_sync_status
     set last_run_at          = now(),
         last_error           = left(coalesce(p_error, '알 수 없는 오류'), 300),
         last_error_at        = now(),
         consecutive_failures = consecutive_failures + 1,
         retry_after          = coalesce(p_retry_after, retry_after)
   where id
  returning consecutive_failures into v_n;
  return coalesce(v_n, 0);
end;
$$;

comment on function public.naver_sync_failed(text, timestamptz) is '네이버 예약 확인 실패 기록. service_role 전용';

revoke all on function public.naver_apply_snapshot(timestamptz, timestamptz, jsonb) from public, anon, authenticated;
revoke all on function public.naver_sync_failed(text, timestamptz) from public, anon, authenticated;
grant execute on function public.naver_apply_snapshot(timestamptz, timestamptz, jsonb) to service_role;
grant execute on function public.naver_sync_failed(text, timestamptz) to service_role;

-- ─── 6. 10분마다 ───────────────────────────────────────────────────────────
-- 네이버에 부담을 주지 않는다: 10분에 한 번, 범위 조회 한 번 (6.5 호출 예의). 차단을 받았으면 retry_after 까지 쉰다
do $$
declare
  r record;
begin
  for r in select jobid from cron.job where jobname = 'naver-booking-sync' loop
    perform cron.unschedule(r.jobid);
  end loop;
end;
$$;

select cron.schedule(
  'naver-booking-sync',
  '*/10 * * * *',
  $$
    select private.call_app('/api/cron/naver-sync')
     where coalesce((select s.retry_after from public.naver_sync_status s where s.id), '-infinity'::timestamptz) <= now()
  $$
);
