-- ============================================================================
-- LC 음원: 월별 → 레벨(650·750·850)별 구분 + 교재 이미지 (2026-09-15 Alan 요청)
--
--  * 레벨 목록은 lc_levels 에서 읽는다. 새 레벨이 생기면 행만 추가하면 화면에 나온다.
--  * 교재 이미지는 레벨마다 여러 장 올릴 수 있다. 학생이 자기 교재를 보고 음원을 고르게 한다.
--  * 열람: 지금 수강 중인 수강생 전체 + 스태프. 레벨로 막지 않는다 (학생이 골라 듣는다).
--  * lc_audio_tracks 는 운영 중인 main 코드가 쓰지 않고 행이 0건이라 구조를 바로 바꾼다.
-- ============================================================================

-- ─── 1. 레벨 ───────────────────────────────────────────────────────────────
create table public.lc_levels (
  level       int primary key check (level between 10 and 990),
  sort_order  int not null default 0
);
comment on table public.lc_levels is 'LC 음원·교재 레벨 (목표 점수). 화면의 650 · 750 · 850 탭';

insert into public.lc_levels (level, sort_order) values (650, 1), (750, 2), (850, 3);

-- ─── 2. 음원: 기수·날짜 대신 레벨 ─────────────────────────────────────────────
-- 조회 정책이 term_id 를 참조하므로 먼저 지우고 다시 만든다
drop policy "lc_audio: 수강생·스태프 조회" on public.lc_audio_tracks;

alter table public.lc_audio_tracks
  drop column term_id,
  drop column date,
  add column level int not null references public.lc_levels (level);
create index lc_audio_tracks_level_idx on public.lc_audio_tracks (level);

create policy "lc_audio: 수강생·스태프 조회" on public.lc_audio_tracks
  for select to authenticated
  using ((select private.is_staff()) or (select private.has_term_access(null)));

-- ─── 3. 교재 이미지 ─────────────────────────────────────────────────────────
create table public.lc_textbook_images (
  id            bigint generated by default as identity primary key,
  level         int not null references public.lc_levels (level),
  file_path     text not null unique,                              -- storage: lc-textbooks/{level}/...
  file_name     text not null,
  file_size     bigint check (file_size is null or file_size >= 0),
  content_type  text,
  uploaded_by   uuid references public.profiles (id) on delete set null,
  created_at    timestamptz not null default now()
);
create index lc_textbook_images_level_idx on public.lc_textbook_images (level);
create index lc_textbook_images_uploaded_by_idx on public.lc_textbook_images (uploaded_by);

-- ─── 4. grant + RLS ────────────────────────────────────────────────────────
grant all on public.lc_levels, public.lc_textbook_images to service_role;
grant select on public.lc_levels to authenticated;
grant select, insert, delete on public.lc_textbook_images to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.lc_levels          enable row level security;
alter table public.lc_textbook_images enable row level security;

create policy "lc_levels: 회원 조회" on public.lc_levels
  for select to authenticated using (true);

create policy "lc_textbooks: 수강생·스태프 조회" on public.lc_textbook_images
  for select to authenticated
  using ((select private.is_staff()) or (select private.has_term_access(null)));
create policy "lc_textbooks: 스태프 등록" on public.lc_textbook_images
  for insert to authenticated with check ((select private.is_staff()));
create policy "lc_textbooks: 스태프 삭제" on public.lc_textbook_images
  for delete to authenticated using ((select private.is_staff()));

-- ─── 5. 저장소 (private bucket) ─────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('lc-textbooks', 'lc-textbooks', false, 10 * 1024 * 1024, array['image/*'])
on conflict (id) do nothing;

create policy "lc-textbooks: 수강생·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'lc-textbooks'
    and (
      (select private.is_staff())
      or exists (select 1 from public.lc_textbook_images i where i.file_path = objects.name)
    )
  );
create policy "lc-textbooks: 스태프 업로드" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'lc-textbooks' and (select private.is_staff()));
create policy "lc-textbooks: 스태프 수정" on storage.objects
  for update to authenticated
  using (bucket_id = 'lc-textbooks' and (select private.is_staff()))
  with check (bucket_id = 'lc-textbooks' and (select private.is_staff()));
create policy "lc-textbooks: 스태프 삭제" on storage.objects
  for delete to authenticated
  using (bucket_id = 'lc-textbooks' and (select private.is_staff()));
