-- ============================================================================
-- 관리자 푸시 알림 + 네이버 예약 (2026-09-15 Alan 요청)
--
--  * 알림은 웹 푸시만 쓴다. 스태프(강사·관리자)가 기기마다 "알림 받기"를 누르면 구독이 저장된다.
--  * 알림 종류(등업신청·교재주문·문의·네이버 예약·하루 요약)는 사람마다 켜고 끈다. 행이 없으면 모두 켜짐.
--  * 네이버 예약은 공개 API 가 없어서, 네이버가 보내는 예약 알림(문자·메일 원문)을 연결 주소로 받아
--    날짜·시각을 뽑아 저장한다. 원문의 전화번호는 가려서 보관한다.
--  * 쓰기는 전부 서버(service_role)가 한다. 화면에서는 본인 설정·구독과 스태프 조회만 허용한다.
-- ============================================================================

-- ─── 1. 푸시 구독 (기기별) ────────────────────────────────────────────────────
create table public.push_subscriptions (
  id            bigint generated by default as identity primary key,
  user_id       uuid not null references public.profiles (id) on delete cascade,
  endpoint      text not null unique,
  p256dh        text not null,
  auth          text not null,
  user_agent    text,
  created_at    timestamptz not null default now(),
  last_sent_at  timestamptz
);
create index push_subscriptions_user_id_idx on public.push_subscriptions (user_id);
comment on table public.push_subscriptions is '스태프 기기별 웹 푸시 구독. 발송 실패(404/410) 시 서버가 지운다';

-- ─── 2. 알림 종류별 켜기/끄기 ────────────────────────────────────────────────
create table public.notification_settings (
  user_id            uuid primary key references public.profiles (id) on delete cascade,
  verification       boolean not null default true,   -- 등업신청 접수
  textbook_order     boolean not null default true,   -- 불라방 교재주문
  contact            boolean not null default true,   -- 연락하기 문의
  naver_reservation  boolean not null default true,   -- 네이버 예약
  daily_digest       boolean not null default true,   -- 하루 요약 (스터디 신청 · 숙제 · 신규 가입)
  updated_at         timestamptz not null default now()
);

-- ─── 3. 네이버 예약 ─────────────────────────────────────────────────────────
create table public.naver_reservations (
  id              bigint generated by default as identity primary key,
  dedupe_key      text not null unique,                 -- 예약번호, 없으면 원문 해시
  status          text not null default 'unknown'
                  check (status in ('requested', 'confirmed', 'cancelled', 'changed', 'unknown')),
  item_name       text,                                 -- 예: 역전토익 강사상담
  customer_name   text,                                 -- 가운데 글자를 가린 이름
  reserved_date   date,                                 -- 예약된 날짜 (한국 시간)
  reserved_time   time,                                 -- 예약된 시각
  booking_number  text,
  source          text not null default 'webhook',
  raw_text        text,                                 -- 받은 원문 (전화번호 가림)
  parsed          boolean not null default false,       -- 날짜·시각을 찾았는지
  received_at     timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index naver_reservations_reserved_idx on public.naver_reservations (reserved_date, reserved_time);
create index naver_reservations_received_idx on public.naver_reservations (received_at desc);
comment on table public.naver_reservations is '네이버 예약 알림에서 뽑은 예약. 연결 주소(/api/naver-reservations)로만 들어온다';

-- ─── 4. 권한 ────────────────────────────────────────────────────────────────
grant all on public.push_subscriptions, public.notification_settings, public.naver_reservations to service_role;
grant select on public.push_subscriptions to authenticated;
grant select on public.notification_settings to authenticated;
grant select on public.naver_reservations to authenticated;

alter table public.push_subscriptions    enable row level security;
alter table public.notification_settings enable row level security;
alter table public.naver_reservations    enable row level security;

create policy "push_subscriptions: 본인 조회" on public.push_subscriptions
  for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "notification_settings: 본인 조회" on public.notification_settings
  for select to authenticated
  using ((select auth.uid()) = user_id);

create policy "naver_reservations: 스태프 조회" on public.naver_reservations
  for select to authenticated
  using ((select private.is_staff()));
