-- ============================================================================
-- 수업자료실 — 자료 하나에 파일 여러 개 · 글만 올리기 (2026-10-06 Alan — "게시판이 파일업로드를 안하면 글 올리기 버튼을 눌러도 계속 오류가 나.
-- 여러개 올릴수 있도록 해줘. 그리고 파일업로드를 안하고 글만 적어서 올릴수도 있도록 부탁해. 마지막으로파일을 한번에 여러개 올릴 수 있도록 해줘")
--
--   * 자료 한 건 = 제목 + 안내 · 스크립트 + 파일 0 ~ N개 (게시판 글 하나). 파일은 새 표 class_material_files 에 둔다
--     (숙제 homework_submissions · homework_files 와 같은 꼴). 파일이 없으면 안내가 있어야 한다 — 그 규칙과 파일 수 상한은 서버 액션이 본다.
--   * 조회 = 그 자료가 보이는 사람 (class_materials 조회 정책 그대로 — 학생은 내 과정 칸의 열린 회차, 강사·관리자는 전부). 쓰기는 강사·관리자.
--   * 저장소 class-materials 조회도 이 표의 행이 보이는지로 판정한다 — 남의 칸 · 아직 안 열린 회차의 파일은 서명 URL 도 못 만든다.
--   * 있던 자료의 파일은 **자료와 같은 id 로** 옮긴다 — 자료 하나에 파일 하나였으므로 겹치지 않고, /files/class/{id} 주소가
--     그대로 같은 파일을 가리킨다 (그 주소의 id 는 이제 파일 id 다).
--   * 두 번에 나눈다 (expand → contract). 이 파일은 새 표를 만들어 옮기고, class_materials 의 파일 칸은 **비울 수 있게만** 둔다 —
--     배포하는 몇 분 동안 아직 떠 있는 옛 앱이 그 칸을 읽고 쓰기 때문이다. 칸을 지우는 일은 새 앱이 뜬 뒤 다음 마이그레이션이 한다.
--   * 새 표 = RLS + 정책 + grant 를 이 파일 하나에 (CLAUDE.md 보안 점검).
-- ============================================================================

create table if not exists public.class_material_files (
  id           bigint generated by default as identity primary key,
  material_id  bigint not null references public.class_materials (id) on delete cascade,
  file_path    text not null unique,                 -- storage: class-materials/{level}-{subject}/…
  file_name    text not null check (char_length(file_name) between 1 and 200),
  file_size    bigint check (file_size is null or file_size >= 0),
  content_type text,
  sort_order   int not null default 0,
  created_at   timestamptz not null default now()
);

comment on table public.class_material_files is
  '수업자료실 자료의 파일 (2026-10-06) — 자료(class_materials) 하나에 0 ~ N개. 그 자료가 보이는 사람이 본다, 쓰기는 강사·관리자';

create index if not exists class_material_files_material_idx on public.class_material_files (material_id, sort_order, id);

alter table public.class_material_files enable row level security;

grant select, insert, update, delete on public.class_material_files to authenticated;
grant all on public.class_material_files to service_role;

-- 조회 = 부모 자료가 보이는 사람 — 하위 조회도 class_materials 의 RLS 를 거친다 (homework_files 와 같은 꼴)
drop policy if exists "class_material_files: 자료가 보이는 사람 조회" on public.class_material_files;
create policy "class_material_files: 자료가 보이는 사람 조회" on public.class_material_files
  for select to authenticated
  using (exists (select 1 from public.class_materials m where m.id = class_material_files.material_id));
drop policy if exists "class_material_files: 스태프 등록" on public.class_material_files;
create policy "class_material_files: 스태프 등록" on public.class_material_files
  for insert to authenticated with check ((select private.is_staff()));
drop policy if exists "class_material_files: 스태프 수정" on public.class_material_files;
create policy "class_material_files: 스태프 수정" on public.class_material_files
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
drop policy if exists "class_material_files: 스태프 삭제" on public.class_material_files;
create policy "class_material_files: 스태프 삭제" on public.class_material_files
  for delete to authenticated using ((select private.is_staff()));

-- 있던 파일 옮기기 — 자료와 같은 id (그래서 /files/class/{id} 가 그대로 같은 파일이다)
insert into public.class_material_files (id, material_id, file_path, file_name, file_size, content_type, sort_order, created_at)
select m.id, m.id, m.file_path, coalesce(nullif(left(m.file_name, 200), ''), '파일'), m.file_size, m.content_type, 0, m.created_at
  from public.class_materials m
 where m.file_path is not null
   and not exists (select 1 from public.class_material_files f where f.file_path = m.file_path)
on conflict do nothing;

-- 직접 넣은 id 뒤에서 번호를 이어 간다 (비었으면 1 부터)
select setval(
  pg_get_serial_sequence('public.class_material_files', 'id'),
  greatest(coalesce((select max(id) from public.class_material_files), 0), 1),
  exists (select 1 from public.class_material_files)
);

-- 글만 올린 자료는 파일 칸이 빈다. 칸 자체는 다음 마이그레이션이 지운다 (위 "두 번에 나눈다")
alter table public.class_materials alter column file_path drop not null;
alter table public.class_materials alter column file_name drop not null;
comment on column public.class_materials.file_path is '(쓰지 않는다 — 2026-10-06 부터 파일은 class_material_files. 다음 마이그레이션이 지운다)';
comment on column public.class_materials.file_name is '(쓰지 않는다 — class_material_files)';
comment on column public.class_materials.file_size is '(쓰지 않는다 — class_material_files)';
comment on column public.class_materials.content_type is '(쓰지 않는다 — class_material_files)';
comment on table public.class_materials is
  '수업자료실 — 레벨(lc_levels) × 과목(rc|lc) × 과정(A|B) × 회차 자료(제목 · 안내). 파일은 class_material_files 에 0 ~ N개. 학생은 내 반의 그 회차 수업일부터(private.my_open_rounds), 쓰기는 강사·관리자 (2026-10-05 · 10-06)';

-- ─── 저장소: 파일 표의 행이 보이면 ─────────────────────────────────────────────
-- 옛 정책(20261005100000)은 class_materials.file_path 를 봤다. 옮기는 사이 옛 앱이 올린 파일도 학생에게 열리도록
-- 옛 칸도 함께 본다 — 다음 마이그레이션이 그 갈래를 뺀다
drop policy if exists "class-materials: 내 레벨 수강생·스태프 조회" on storage.objects;
drop policy if exists "class-materials: 자료가 보이는 사람·스태프 조회" on storage.objects;
create policy "class-materials: 자료가 보이는 사람·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'class-materials'
    and (
      (select private.is_staff())
      or exists (select 1 from public.class_material_files f where f.file_path = objects.name)
      or exists (select 1 from public.class_materials m where m.file_path = objects.name)
    )
  );
