-- ============================================================================
-- LC 교재: 레벨 × 반(A·B) × 권 (2026-09-15 Alan 요청)
--
--  * 레벨(650·750·850)마다 A반 교재 2권 + B반 교재 2권 = 4권.
--    홀수달은 A반, 짝수달은 B반 교재로 수업한다 (이번 달 표시는 화면이 월의 홀짝으로 계산).
--  * 교재(lc_books)마다 표지 이미지 1장 + 교재명 + 짧은 설명. 음원은 교재에 속한다.
--  * 레벨을 새로 추가하면 트리거가 A·B 반의 1·2권 칸을 만든다.
--  * 운영 중인 이전 코드가 lc_textbook_images · lc_audio_tracks.level 을 읽으므로 이번에는 추가만 한다.
--    새 코드가 배포되면 정리 마이그레이션에서 지운다.
-- ============================================================================

-- ─── 1. 교재 ───────────────────────────────────────────────────────────────
create table public.lc_books (
  id           bigint generated by default as identity primary key,
  level        int not null references public.lc_levels (level),
  book_set     text not null check (book_set in ('A', 'B')),          -- A반(홀수달) · B반(짝수달)
  volume       int not null check (volume between 1 and 9),           -- 권
  title        text check (title is null or char_length(title) <= 60),
  description  text check (description is null or char_length(description) <= 200),
  cover_path   text unique,                                            -- storage: lc-textbooks/{level}/...
  cover_name   text,
  cover_size   bigint check (cover_size is null or cover_size >= 0),
  cover_type   text,
  updated_by   uuid references public.profiles (id) on delete set null,
  updated_at   timestamptz not null default now(),
  unique (level, book_set, volume),
  check ((cover_path is null) = (cover_name is null))
);
create index lc_books_updated_by_idx on public.lc_books (updated_by);
comment on table public.lc_books is 'LC 교재. 레벨마다 A반(홀수달) 2권 + B반(짝수달) 2권';

insert into public.lc_books (level, book_set, volume)
select l.level, s.book_set, v.volume
from public.lc_levels l
cross join (values ('A'), ('B')) as s (book_set)
cross join (values (1), (2)) as v (volume);

-- 새 레벨 → 교재 칸 4개
create or replace function private.lc_levels_create_books()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.lc_books (level, book_set, volume)
  select new.level, s.book_set, v.volume
  from (values ('A'), ('B')) as s (book_set)
  cross join (values (1), (2)) as v (volume)
  on conflict (level, book_set, volume) do nothing;
  return new;
end;
$$;

revoke execute on function private.lc_levels_create_books() from public, anon, authenticated;

create trigger lc_levels_create_books
  after insert on public.lc_levels
  for each row execute function private.lc_levels_create_books();

-- ─── 2. 음원 → 교재 연결 (배포 전까지 level 도 남겨 둔다) ─────────────────────
alter table public.lc_audio_tracks
  add column book_id bigint references public.lc_books (id),
  alter column level drop not null;
create index lc_audio_tracks_book_id_idx on public.lc_audio_tracks (book_id);

-- ─── 3. 표지 파일 조회: 이전 이미지 묶음 또는 교재 표지 ────────────────────────
drop policy "lc-textbooks: 수강생·스태프 조회" on storage.objects;
create policy "lc-textbooks: 수강생·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'lc-textbooks'
    and (
      (select private.is_staff())
      or exists (select 1 from public.lc_books b where b.cover_path = objects.name)
      or exists (select 1 from public.lc_textbook_images i where i.file_path = objects.name)
    )
  );

-- ─── 4. grant + RLS ────────────────────────────────────────────────────────
-- 교재 칸은 레벨이 만들고, 화면에서는 표지·교재명·설명만 고친다
grant all on public.lc_books to service_role;
grant select on public.lc_books to authenticated;
grant update (title, description, cover_path, cover_name, cover_size, cover_type, updated_by, updated_at)
  on public.lc_books to authenticated;

alter table public.lc_books enable row level security;

create policy "lc_books: 수강생·스태프 조회" on public.lc_books
  for select to authenticated
  using ((select private.is_staff()) or (select private.has_term_access(null)));
create policy "lc_books: 스태프 수정" on public.lc_books
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
