-- ============================================================================
-- 수업자료실 공지사항 (2026-10-05 Alan — "수업자료실에서 1회차 앞에 공지사항을 올릴 수 있는 곳이 있으면 좋겠어. … 공지사항을 여러개 올릴 수도" ·
--   "안내글에서 쓰는 글 편집기능이 다 들어가면 좋겠어. 추가적으로 이미지도 중간에 추가 … 블로그랑 같다고 생각하면" ·
--   범위: "강사가 직접 지정할 수 있으면 좋겠어. 전체공지인지, 레벨별이라면 레벨을 선택, RC LC도 선택" · "해당 공지 페이지가 새로 열리면 좋겠어")
--
--   * 강사·관리자가 /admin/class-materials 에서 올린다 (조교 아님 — 관리자 화면 여섯 가지는 Alan 이 정했다).
--   * 범위: levels(비우면 모든 레벨) × subjects(비우면 RC · LC 둘 다). 둘 다 비우면 전체 공지.
--   * 학생은 **지금 수강 중(개강일~종강일)** 일 때만 본다:
--       - 전체 공지 = private.has_term_access(null)
--       - 범위 공지 = 내 과정 칸(private.my_round_cells — 'level:subject:set') 중 하나가 레벨 · 과목에 맞는다.
--         RC 단과 학생에게는 LC 공지가 없다 (자료와 같은 규칙). 앱 noticeVisible(src/lib/class-notices.ts)과 같은 규칙.
--   * 본문은 class_materials.note 와 같은 꺾쇠 태그 글이고 그림은 [img=images/….webp w=50] 로 경로만 든다.
--     그림 파일은 private 버킷 class-notices — 조회는 **그 그림을 품은 공지가 보이는 사람**만 (공지 행 RLS 를 그대로 거친다).
--   * 작성자 이름은 author_name 에 박아 둔다 — 학생은 profiles 를 못 읽는다 (알림함 sender_name 과 같은 까닭).
--   * 새 표 = RLS + 정책 + grant 를 이 파일 하나에 (CLAUDE.md 보안 점검).
-- ============================================================================

create table if not exists public.class_notices (
  id          bigint generated by default as identity primary key,
  title       text not null check (char_length(title) between 1 and 100),
  body        text not null default '' check (char_length(body) <= 50000),
  levels      int[] not null default '{}',
  subjects    text[] not null default '{}' check (subjects <@ array['rc', 'lc']::text[]),
  author_id   uuid references public.profiles (id) on delete set null,
  author_name text check (author_name is null or char_length(author_name) <= 40),
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

comment on table public.class_notices is
  '수업자료실 공지 (2026-10-05) — 범위 levels × subjects(비우면 전체). 학생은 수강 중 + 내 과정 칸이 맞을 때, 쓰기는 강사·관리자';

create index if not exists class_notices_created_idx on public.class_notices (created_at desc);
create index if not exists class_notices_author_idx on public.class_notices (author_id);

alter table public.class_notices enable row level security;

grant select, insert, update, delete on public.class_notices to authenticated;
grant all on public.class_notices to service_role;

create policy "class_notices: 범위 수강생·스태프 조회" on public.class_notices
  for select to authenticated
  using (
    (select private.is_staff())
    or (
      cardinality(levels) = 0 and cardinality(subjects) = 0
      and (select private.has_term_access(null))
    )
    or exists (
      select 1
      from unnest((select private.my_round_cells())) as c(cell)
      where (cardinality(levels) = 0 or split_part(c.cell, ':', 1)::int = any (levels))
        and (cardinality(subjects) = 0 or split_part(c.cell, ':', 2) = any (subjects))
    )
  );
create policy "class_notices: 스태프 등록" on public.class_notices
  for insert to authenticated with check ((select private.is_staff()));
create policy "class_notices: 스태프 수정" on public.class_notices
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "class_notices: 스태프 삭제" on public.class_notices
  for delete to authenticated using ((select private.is_staff()));

-- ─── 공지 그림 (private) ────────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('class-notices', 'class-notices', false, 10 * 1024 * 1024, array['image/jpeg', 'image/png', 'image/webp', 'image/gif'])
on conflict (id) do nothing;

-- 조회 = 그 그림을 본문에 품은 공지를 볼 수 있는 사람 (위 정책 — 학생은 내 범위 공지만). 쓰기는 강사·관리자
create policy "class-notices: 공지 보는 사람·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'class-notices'
    and (
      (select private.is_staff())
      or exists (select 1 from public.class_notices n where position(('[img=' || objects.name) in n.body) > 0)
    )
  );
create policy "class-notices: 스태프 업로드" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'class-notices' and (select private.is_staff()));
create policy "class-notices: 스태프 수정" on storage.objects
  for update to authenticated
  using (bucket_id = 'class-notices' and (select private.is_staff()))
  with check (bucket_id = 'class-notices' and (select private.is_staff()));
create policy "class-notices: 스태프 삭제" on storage.objects
  for delete to authenticated
  using (bucket_id = 'class-notices' and (select private.is_staff()));
