-- ============================================================================
-- 스터디 3종 · 숙제제출 · LC 음원 (2026-09-15 Alan 요청)
--
--  * 스터디는 기수(월)마다 강사가 연다. 유형은 세 가지:
--      offline (대면스터디) — 강사가 그 달 시간대(study_slots)를 정하고, 수강생이 시간대를 골라 신청
--      online  (비대면스터디) — 신청하면 수업일마다 하루 하나씩 올라오는 자료(study_materials)를 받는다
--      vocab   (단어스터디) — 대면과 같이 시간대를 골라 신청, 그 시간에 단어 점검
--    하루 2타임·3타임처럼 시간대 개수는 달마다 자유 → 시간대는 행으로 둔다.
--  * 신청 자격: 그 달 반에 배정된 수강생 (개강 전 예비등록생 포함, 종강일까지).
--    자료·음원 열람은 수강 중(active)인 수강생만. 비대면 자료는 해당 날짜부터 공개.
--  * 숙제제출: 비대면 자료(날짜)마다 수강생이 풀이 파일(여러 장)을 올리고, 강사가 점검완료 처리.
--  * LC 음원: 강사가 올린 음원을 그 달 수강생이 듣는다. term_id 가 null 이면 상시 공개.
--  * 파일은 전부 private 버킷. 다운로드는 서명 URL — storage 정책이 아래 테이블 RLS 를 그대로 따른다.
--  * 기존 study_applications(자유 양식·비회원 신청)는 운영 중인 main 코드가 아직 쓰므로 이번에
--    지우지 않는다. 새 신청은 study_signups 에 쌓이고, 배포 후 별도 마이그레이션으로 정리한다.
-- ============================================================================

-- ─── 1. RLS 헬퍼 ───────────────────────────────────────────────────────────

-- 그 달(term) 반에 배정된 수강생인가 — 스터디 신청 자격. 예비등록생(preliminary) 포함
create or replace function private.is_term_enrollee(p_term_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.enrollments e
    join public.enrollment_orders o on o.id = e.order_id
    join public.class_sections s on s.id = e.section_id
    where e.student_id = (select auth.uid())
      and s.term_id = p_term_id
      and e.status = 'active'
      and o.status in ('preliminary', 'active')
      and private.today_kst() <= s.closes_at
  )
$$;

-- 콘텐츠(비대면 자료·LC 음원) 열람 — has_section_access 의 기수 버전.
-- p_term_id 가 null 이면 "지금 수강 중인 반이 하나라도 있는가" (상시 공개 음원용)
create or replace function private.has_term_access(p_term_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.user_role() in ('student', 'instructor', 'admin')
     and exists (
       select 1
       from public.enrollments e
       join public.enrollment_orders o on o.id = e.order_id
       join public.class_sections s on s.id = e.section_id
       where e.student_id = (select auth.uid())
         and (p_term_id is null or s.term_id = p_term_id)
         and e.status = 'active'
         and o.status = 'active'
         and private.today_kst() <= s.closes_at
     )
$$;

grant execute on function
  private.is_term_enrollee(bigint),
  private.has_term_access(bigint)
to authenticated, service_role;

-- ─── 2. 스터디 ─────────────────────────────────────────────────────────────

create table public.studies (
  id          bigint generated by default as identity primary key,
  term_id     bigint not null references public.terms (id),
  kind        text not null check (kind in ('offline', 'online', 'vocab')),
  status      text not null default 'draft' check (status in ('draft', 'open', 'closed')),
  notice      text check (notice is null or char_length(notice) <= 1000),  -- 장소·요일·준비물 안내
  created_at  timestamptz not null default now(),
  unique (term_id, kind)
);
comment on table public.studies is '월별 스터디. kind: offline=대면, online=비대면, vocab=단어. status: draft 비공개 / open 신청 중 / closed 신청 마감';

-- 대면·단어 스터디 시간대. 강사가 그 달 편성 때 함께 정한다
create table public.study_slots (
  id             bigint generated by default as identity primary key,
  study_id       bigint not null references public.studies (id) on delete cascade,
  start_time     time not null,
  end_time       time not null,
  capacity       int check (capacity is null or capacity > 0),     -- null = 정원 없음
  applied_count  int not null default 0 check (applied_count >= 0),
  created_at     timestamptz not null default now(),
  check (end_time > start_time),
  unique (study_id, start_time),
  unique (id, study_id)                                             -- study_signups 복합 FK 대상
);
comment on column public.study_slots.applied_count is '신청 인원. study_signups 트리거가 유지한다 (직접 수정 불가)';

-- 스터디 신청. 한 스터디(유형)에 한 시간대만
create table public.study_signups (
  id          bigint generated by default as identity primary key,
  study_id    bigint not null references public.studies (id),     -- 신청자가 있는 스터디는 삭제 불가
  slot_id     bigint,                                              -- 대면·단어는 필수, 비대면은 null
  user_id     uuid not null references public.profiles (id) on delete cascade,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (study_id, user_id),
  foreign key (slot_id, study_id) references public.study_slots (id, study_id)  -- 신청자가 있는 시간대는 삭제 불가
);
create index study_signups_user_id_idx on public.study_signups (user_id);
create index study_signups_slot_idx on public.study_signups (slot_id, study_id) where slot_id is not null;

-- 비대면 자료. 수업일마다 하루 하나
create table public.study_materials (
  id            bigint generated by default as identity primary key,
  study_id      bigint not null references public.studies (id),   -- 자료가 있는 스터디는 삭제 불가
  date          date not null,
  title         text check (title is null or char_length(title) <= 100),
  file_path     text not null unique,                              -- storage: study-materials/{study_id}/...
  file_name     text not null,                                     -- 원본 파일명 (다운로드 이름)
  file_size     bigint check (file_size is null or file_size >= 0),
  content_type  text,
  uploaded_by   uuid references public.profiles (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  unique (study_id, date)
);
create index study_materials_uploaded_by_idx on public.study_materials (uploaded_by);

-- ─── 3. 숙제제출 ───────────────────────────────────────────────────────────

create table public.homework_submissions (
  id           bigint generated by default as identity primary key,
  material_id  bigint not null references public.study_materials (id),  -- 제출물이 있는 자료는 삭제 불가
  user_id      uuid not null references public.profiles (id) on delete cascade,
  status       text not null default 'submitted' check (status in ('submitted', 'checked')),
  checked_by   uuid references public.profiles (id) on delete set null,
  checked_at   timestamptz,
  created_at   timestamptz not null default now(),
  unique (material_id, user_id),
  check ((status = 'checked') = (checked_at is not null))
);
create index homework_submissions_user_id_idx on public.homework_submissions (user_id);
create index homework_submissions_checked_by_idx on public.homework_submissions (checked_by);

-- 제출 파일 (사진 여러 장 가능)
create table public.homework_files (
  id             bigint generated by default as identity primary key,
  submission_id  bigint not null references public.homework_submissions (id) on delete cascade,
  file_path      text not null unique,                             -- storage: homework/{user_id}/{material_id}/...
  file_name      text not null,
  file_size      bigint check (file_size is null or file_size >= 0),
  content_type   text,
  created_at     timestamptz not null default now()
);
create index homework_files_submission_id_idx on public.homework_files (submission_id);

-- ─── 4. LC 음원 ────────────────────────────────────────────────────────────

create table public.lc_audio_tracks (
  id            bigint generated by default as identity primary key,
  term_id       bigint references public.terms (id),              -- null = 상시 공개
  title         text not null check (char_length(title) between 1 and 100),
  date          date,                                              -- 선택: 해당 수업일
  file_path     text not null unique,                              -- storage: lc-audio/...
  file_name     text not null,
  file_size     bigint check (file_size is null or file_size >= 0),
  content_type  text,
  uploaded_by   uuid references public.profiles (id) on delete set null,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);
create index lc_audio_tracks_term_date_idx on public.lc_audio_tracks (term_id, date);
create index lc_audio_tracks_uploaded_by_idx on public.lc_audio_tracks (uploaded_by);

-- ─── 5. 신청 트리거: 유형별 시간대 규칙 + 정원 ─────────────────────────────
-- applied_count 를 조건부로 올리므로 마지막 한 자리에 동시에 신청해도 정원을 넘지 않는다.
create or replace function private.study_signups_sync()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_kind text;
begin
  if tg_op <> 'DELETE' then
    select s.kind into v_kind from public.studies s where s.id = new.study_id;
    if (v_kind = 'online') <> (new.slot_id is null) then
      raise exception 'study_slot_rule'
        using errcode = '23514', detail = '비대면 스터디는 시간대 없이, 대면·단어 스터디는 시간대를 골라 신청합니다.';
    end if;
  end if;

  -- 시간대를 옮기거나 취소하면 이전 시간대 자리를 돌려준다
  if tg_op in ('UPDATE', 'DELETE') and old.slot_id is not null
     and (tg_op = 'DELETE' or new.slot_id is distinct from old.slot_id) then
    update public.study_slots
    set applied_count = greatest(applied_count - 1, 0)
    where id = old.slot_id;
  end if;

  -- 새 시간대는 정원 안에서만 차지한다
  if tg_op in ('INSERT', 'UPDATE') and new.slot_id is not null
     and (tg_op = 'INSERT' or new.slot_id is distinct from old.slot_id) then
    update public.study_slots
    set applied_count = applied_count + 1
    where id = new.slot_id
      and (capacity is null or applied_count < capacity);
    if not found then
      raise exception 'study_slot_full' using errcode = 'P0001', detail = '이 시간대는 정원이 찼습니다.';
    end if;
  end if;

  if tg_op = 'DELETE' then
    return old;
  end if;
  new.updated_at := now();
  return new;
end;
$$;

revoke execute on function private.study_signups_sync() from public, anon, authenticated;

create trigger study_signups_sync
  before insert or update or delete on public.study_signups
  for each row execute function private.study_signups_sync();

-- ─── 6. grant ──────────────────────────────────────────────────────────────
grant all on
  public.studies, public.study_slots, public.study_signups, public.study_materials,
  public.homework_submissions, public.homework_files, public.lc_audio_tracks
to service_role;

-- 비회원: 공개 스터디 일정만
grant select on public.studies, public.study_slots to anon;

-- 로그인 회원: 행은 RLS 가, 민감한 컬럼은 컬럼 단위 grant 가 제한한다
grant select, insert, delete on public.studies to authenticated;
grant update (status, notice) on public.studies to authenticated;                       -- 기수·유형은 만든 뒤 못 바꾼다
grant select, delete on public.study_slots to authenticated;
grant insert (study_id, start_time, end_time, capacity) on public.study_slots to authenticated;
grant update (start_time, end_time, capacity) on public.study_slots to authenticated;   -- applied_count 는 트리거만
grant select, delete on public.study_signups to authenticated;
grant insert (study_id, slot_id, user_id) on public.study_signups to authenticated;
grant update (slot_id) on public.study_signups to authenticated;                         -- 시간대 변경만
grant select, insert, update, delete on public.study_materials to authenticated;
grant select, delete on public.homework_submissions to authenticated;
grant insert (material_id, user_id) on public.homework_submissions to authenticated;
grant update (status, checked_by, checked_at) on public.homework_submissions to authenticated;
grant select, insert, delete on public.homework_files to authenticated;
grant select, insert, update, delete on public.lc_audio_tracks to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ─── 7. RLS ────────────────────────────────────────────────────────────────
alter table public.studies              enable row level security;
alter table public.study_slots          enable row level security;
alter table public.study_signups        enable row level security;
alter table public.study_materials      enable row level security;
alter table public.homework_submissions enable row level security;
alter table public.homework_files       enable row level security;
alter table public.lc_audio_tracks      enable row level security;

-- studies: draft 제외 공개 조회 (class_sections 와 같은 방식), 스태프 관리
create policy "studies: 비회원 조회" on public.studies
  for select to anon
  using (status <> 'draft');
create policy "studies: 회원 조회" on public.studies
  for select to authenticated
  using (status <> 'draft' or (select private.is_staff()));
create policy "studies: 스태프 등록" on public.studies
  for insert to authenticated with check ((select private.is_staff()));
create policy "studies: 스태프 수정" on public.studies
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "studies: 스태프 삭제" on public.studies
  for delete to authenticated using ((select private.is_staff()));

-- study_slots: 볼 수 있는 스터디의 시간대만 (studies RLS 를 따른다), 스태프 관리
create policy "study_slots: 조회" on public.study_slots
  for select to anon, authenticated
  using (exists (select 1 from public.studies s where s.id = study_slots.study_id));
create policy "study_slots: 스태프 등록" on public.study_slots
  for insert to authenticated
  with check (
    (select private.is_staff())
    and exists (select 1 from public.studies s where s.id = study_slots.study_id and s.kind in ('offline', 'vocab'))
  );
create policy "study_slots: 스태프 수정" on public.study_slots
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "study_slots: 스태프 삭제" on public.study_slots
  for delete to authenticated using ((select private.is_staff()));

-- study_signups: 본인·스태프 조회. 신청·변경·취소는 신청 중(open)인 스터디에 그 달 수강생만
create policy "study_signups: 본인·스태프 조회" on public.study_signups
  for select to authenticated
  using ((select auth.uid()) = user_id or (select private.is_staff()));
create policy "study_signups: 수강생 신청" on public.study_signups
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.studies s
      where s.id = study_signups.study_id
        and s.status = 'open'
        and private.is_term_enrollee(s.term_id)
    )
  );
create policy "study_signups: 본인 시간대 변경" on public.study_signups
  for update to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and exists (
      select 1 from public.studies s
      where s.id = study_signups.study_id
        and s.status = 'open'
        and private.is_term_enrollee(s.term_id)
    )
  );
create policy "study_signups: 본인 취소·스태프 정리" on public.study_signups
  for delete to authenticated
  using (
    (select private.is_staff())
    or (
      (select auth.uid()) = user_id
      and exists (select 1 from public.studies s where s.id = study_signups.study_id and s.status = 'open')
    )
  );

-- study_materials: 신청자는 수강 중이고 해당 날짜가 됐을 때만, 스태프는 전부. 비대면 스터디에만 등록
create policy "study_materials: 신청자·스태프 조회" on public.study_materials
  for select to authenticated
  using (
    (select private.is_staff())
    or (
      study_materials.date <= (select private.today_kst())
      and exists (
        select 1
        from public.study_signups g
        join public.studies s on s.id = g.study_id
        where g.study_id = study_materials.study_id
          and g.user_id = (select auth.uid())
          and private.has_term_access(s.term_id)
      )
    )
  );
create policy "study_materials: 스태프 등록" on public.study_materials
  for insert to authenticated
  with check (
    (select private.is_staff())
    and exists (select 1 from public.studies s where s.id = study_materials.study_id and s.kind = 'online')
  );
create policy "study_materials: 스태프 수정" on public.study_materials
  for update to authenticated
  using ((select private.is_staff()))
  with check (
    (select private.is_staff())
    and exists (select 1 from public.studies s where s.id = study_materials.study_id and s.kind = 'online')
  );
create policy "study_materials: 스태프 삭제" on public.study_materials
  for delete to authenticated using ((select private.is_staff()));

-- homework_submissions: 볼 수 있는 자료에만 본인 제출. 점검(status)은 스태프만, 점검 전에는 본인이 철회 가능
create policy "homework_submissions: 본인·스태프 조회" on public.homework_submissions
  for select to authenticated
  using ((select auth.uid()) = user_id or (select private.is_staff()));
create policy "homework_submissions: 본인 제출" on public.homework_submissions
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and status = 'submitted'
    and exists (select 1 from public.study_materials m where m.id = homework_submissions.material_id)
  );
create policy "homework_submissions: 스태프 점검" on public.homework_submissions
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "homework_submissions: 점검 전 본인 철회" on public.homework_submissions
  for delete to authenticated
  using ((select auth.uid()) = user_id and status = 'submitted');

-- homework_files: 제출물 접근 규칙을 따른다. 추가·삭제는 점검 전 본인만
create policy "homework_files: 본인·스태프 조회" on public.homework_files
  for select to authenticated
  using (exists (select 1 from public.homework_submissions s where s.id = homework_files.submission_id));
create policy "homework_files: 점검 전 본인 추가" on public.homework_files
  for insert to authenticated
  with check (
    split_part(homework_files.file_path, '/', 1) = (select auth.uid())::text
    and exists (
      select 1 from public.homework_submissions s
      where s.id = homework_files.submission_id
        and s.user_id = (select auth.uid())
        and s.status = 'submitted'
    )
  );
create policy "homework_files: 점검 전 본인 삭제" on public.homework_files
  for delete to authenticated
  using (
    exists (
      select 1 from public.homework_submissions s
      where s.id = homework_files.submission_id
        and s.user_id = (select auth.uid())
        and s.status = 'submitted'
    )
  );

-- lc_audio_tracks: 그 달 수강생(term_id null 이면 현재 수강생 전체)·스태프 조회, 스태프 관리
create policy "lc_audio: 수강생·스태프 조회" on public.lc_audio_tracks
  for select to authenticated
  using ((select private.is_staff()) or private.has_term_access(lc_audio_tracks.term_id));
create policy "lc_audio: 스태프 등록" on public.lc_audio_tracks
  for insert to authenticated with check ((select private.is_staff()));
create policy "lc_audio: 스태프 수정" on public.lc_audio_tracks
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "lc_audio: 스태프 삭제" on public.lc_audio_tracks
  for delete to authenticated using ((select private.is_staff()));

-- ─── 8. 파일 저장소 (private bucket) ────────────────────────────────────────
-- 프로젝트 전역 업로드 한도가 50MB 라 버킷 한도도 그 안에서 잡는다.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  ('study-materials', 'study-materials', false, 50 * 1024 * 1024, null),               -- 스태프만 올림 (pdf·hwp·docx·zip 등)
  ('homework',        'homework',        false, 20 * 1024 * 1024, array['image/*', 'application/pdf']),
  ('lc-audio',        'lc-audio',        false, 50 * 1024 * 1024, array['audio/*'])
on conflict (id) do nothing;

-- study-materials: 조회는 study_materials 행을 볼 수 있는 사람(날짜 공개 규칙 포함), 쓰기는 스태프
create policy "study-materials: 신청자·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'study-materials'
    and (
      (select private.is_staff())
      or exists (select 1 from public.study_materials m where m.file_path = objects.name)
    )
  );
create policy "study-materials: 스태프 업로드" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'study-materials' and (select private.is_staff()));
create policy "study-materials: 스태프 수정" on storage.objects
  for update to authenticated
  using (bucket_id = 'study-materials' and (select private.is_staff()))
  with check (bucket_id = 'study-materials' and (select private.is_staff()));
create policy "study-materials: 스태프 삭제" on storage.objects
  for delete to authenticated
  using (bucket_id = 'study-materials' and (select private.is_staff()));

-- homework: 경로 규칙 homework/{auth.uid()}/{material_id}/{file}
create policy "homework: 본인 폴더 업로드" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'homework'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "homework: 본인·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'homework'
    and ((storage.foldername(name))[1] = (select auth.uid())::text or (select private.is_staff()))
  );
create policy "homework: 점검 전 본인 삭제" on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'homework'
    and (storage.foldername(name))[1] = (select auth.uid())::text
    and not exists (
      select 1
      from public.homework_files f
      join public.homework_submissions s on s.id = f.submission_id
      where f.file_path = objects.name
        and s.status = 'checked'
    )
  );

-- lc-audio: 조회는 lc_audio_tracks 행을 볼 수 있는 사람, 쓰기는 스태프
create policy "lc-audio: 수강생·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'lc-audio'
    and (
      (select private.is_staff())
      or exists (select 1 from public.lc_audio_tracks t where t.file_path = objects.name)
    )
  );
create policy "lc-audio: 스태프 업로드" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'lc-audio' and (select private.is_staff()));
create policy "lc-audio: 스태프 수정" on storage.objects
  for update to authenticated
  using (bucket_id = 'lc-audio' and (select private.is_staff()))
  with check (bucket_id = 'lc-audio' and (select private.is_staff()));
create policy "lc-audio: 스태프 삭제" on storage.objects
  for delete to authenticated
  using (bucket_id = 'lc-audio' and (select private.is_staff()));
