-- ============================================================================
-- QR 출석 — 입실 · 퇴실 (2026-09-21 Alan — "출석을 범위에 넣어줘. 입실과 퇴실 다 받자! 조교에게도 명단을 열어줘")
--
--   첫토익 문서 02 의 "1인 강사·작은 학원용 최소 구성" 을 따랐다:
--   * **QR 은 주소형 · 30초마다 바뀐다** — 교실 화면(/admin/attendance/qr, 강사·조교)이 `https://winnertoeic.com/attend?t=토큰` QR 과
--     6자리 코드를 띄운다. 학생은 휴대폰 기본 카메라로 찍거나(앱 안 스캐너가 필요 없다 — 사이트는 응답 헤더로 카메라를 꺼 두었다)
--     앱의 "출석" 화면에 코드를 친다. 토큰은 **지금 칸과 앞 세 칸(2분)** 만 받는다 — 단톡방에 올린 사진은 곧 쓸모가 없어진다.
--     토큰은 DB 안의 비밀(Vault attendance_qr_secret)로 만든 HMAC 이라 앱·저장소에 값이 없다.
--   * **판정은 전부 이 파일의 함수가 한다** (public.attendance_scan) — 시각은 서버 now() 만, 반·교시도 서버가 학생 배정으로 정한다.
--     학생은 표에 직접 못 쓴다 (첫토익 5.4 — 학생이 이벤트를 넣고 트리거가 도장을 만드는 구조는 우회 길이 된다).
--   * 규칙은 첫토익 값 그대로 (Alan 이 따로 정하지 않았다): 입실은 수업 시작 **30분 전 ~ 끝**, 시작 **7분 뒤**부터 지각,
--     입실하고 **30분 안** 에 다시 찍으면 "이미 입실" (연달아 찍은 것), 그 뒤에 찍으면 **퇴실** — 퇴실은 수업이 끝나고 30분까지.
--   * 대상은 **현장 수강생** 이다 — 불라방(mode = live)은 교실에 오지 않고, 저녁 화목금 인강 날(recorded)은 녹화본을 본다.
--     한 칸 = (학생, **직접 배정된 반**, 날짜). 120분 학생은 하루 한 칸이다. 회차 id 는 편성을 고치면 바뀌어 쓰지 않는다.
--   * **강사 판정은 자동 판정이 덮지 못한다** — 출석 인정·결석은 강사·조교가 사유를 적어 정하고(public.attendance_set),
--     그 뒤 학생이 찍어도 "이미 처리됨" 이다. 출석 인정은 지각 표시를 지운다 (첫토익 11).
--   * 조교에게도 연다 (Alan). 명단·QR 화면·출석 인정/결석 모두 crew.
-- ============================================================================

-- ─── 1. 출석 도장 (한 칸 = 학생 · 반 · 날짜) ──────────────────────────────
create table if not exists public.attendance_stamps (
  id           bigint generated by default as identity primary key,
  student_id   uuid not null references public.profiles (id) on delete cascade,
  section_id   bigint not null references public.class_sections (id) on delete cascade,
  class_date   date not null,
  status       text not null check (status in ('in', 'out', 'manual', 'absent')),
  check_in_at  timestamptz,
  check_out_at timestamptz,
  late         boolean not null default false,
  method       text check (method is null or method in ('qr', 'code', 'manual')),
  decided_by   uuid references public.profiles (id) on delete set null,
  decided_note text check (decided_note is null or char_length(decided_note) <= 200),
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  unique (student_id, section_id, class_date)
);

create index if not exists attendance_stamps_date_idx on public.attendance_stamps (class_date, section_id);

comment on table public.attendance_stamps is
  'QR 출석 (2026-09-21). status: in(입실만) · out(입실+퇴실 = 출석) · manual(강사 출석 인정) · absent(강사 결석 처리)';

-- ─── 2. 기록 (쌓기만) — 부정 여부를 나중에 볼 근거, 틀린 코드 연타 막기 ───
create table if not exists public.attendance_events (
  id         bigint generated by default as identity primary key,
  student_id uuid references public.profiles (id) on delete cascade,
  section_id bigint references public.class_sections (id) on delete set null,
  class_date date,
  kind       text not null check (kind in ('enter', 'exit', 'manual', 'reject')),
  method     text,
  result     text not null,
  actor_id   uuid references public.profiles (id) on delete set null,
  note       text,
  created_at timestamptz not null default now()
);

create index if not exists attendance_events_student_idx on public.attendance_events (student_id, created_at desc);

grant select on public.attendance_stamps, public.attendance_events to authenticated;
grant all on public.attendance_stamps, public.attendance_events to service_role;

alter table public.attendance_stamps enable row level security;
alter table public.attendance_events enable row level security;

create policy "attendance_stamps: 본인·스태프·조교 조회" on public.attendance_stamps
  for select to authenticated using ((select auth.uid()) = student_id or (select private.is_crew()));
create policy "attendance_events: 스태프·조교 조회" on public.attendance_events
  for select to authenticated using ((select private.is_crew()));

-- ─── 3. 30초마다 바뀌는 토큰 · 6자리 코드 ──────────────────────────────────
do $$
begin
  if not exists (select 1 from vault.secrets where name = 'attendance_qr_secret') then
    perform vault.create_secret(
      encode(extensions.gen_random_bytes(32), 'hex'),
      'attendance_qr_secret',
      'QR 출석 토큰(HMAC)의 비밀. 마이그레이션 20260921130500 이 DB 안에서 만들었다'
    );
  end if;
end;
$$;

-- 30초 칸 하나의 토큰(12자, QR 주소에 들어간다)과 6자리 코드(손으로 친다)
create or replace function private.attendance_token(p_step bigint)
returns table (token text, code text)
language sql
stable
security definer
set search_path = ''
as $$
  with h as (
    select encode(
             extensions.hmac(p_step::text, (select s.decrypted_secret from vault.decrypted_secrets s where s.name = 'attendance_qr_secret' limit 1), 'sha256'),
             'hex') as hex
  )
  select upper(substr(h.hex, 1, 12)),
         lpad(((('x' || substr(h.hex, 13, 8))::bit(32)::bigint) % 1000000)::text, 6, '0')
    from h
$$;

revoke all on function private.attendance_token(bigint) from public, anon, authenticated;

-- 교실 화면용: 지금 칸의 토큰·코드와 바뀌는 시각. 강사·관리자·조교만
create or replace function public.attendance_display()
returns jsonb
language plpgsql
stable
security definer
set search_path = ''
as $$
declare
  v_step bigint := floor(extract(epoch from now()) / 30)::bigint;
  t      record;
begin
  if not private.is_crew() then
    raise exception 'forbidden';
  end if;
  select * into t from private.attendance_token(v_step);
  return jsonb_build_object('token', t.token, 'code', t.code, 'expires_at', to_timestamp((v_step + 1) * 30));
end;
$$;

-- ─── 4. 오늘 교실에 와야 하는 내 반 ────────────────────────────────────────
-- 직접 배정 · 현장 · 인강 반 아님 · 수강 중(active) · 그 날 회차가 있음
create or replace function private.attendance_sessions(p_uid uuid, p_date date)
returns table (section_id bigint, label text, starts timestamp, ends timestamp)
language sql
stable
security definer
set search_path = ''
as $$
  select distinct
         s.id,
         concat_ws(' ', c.name, case s.track when 'mwf' then '월수금' else '화목금' end, s.time_block),
         p_date + private.time_block_start(s.time_block),
         p_date + private.time_block_end(s.time_block)
    from public.enrollments e
    join public.enrollment_orders o on o.id = e.order_id
    join public.class_sections s on s.id = e.section_id
    join public.courses c on c.id = s.course_id
    join public.session_dates d on d.section_id = s.id and d.date = p_date
   where e.student_id = p_uid
     and e.status = 'active'
     and o.status = 'active'
     and e.mode = 'onsite'
     and not s.recorded
     and p_date <= s.closes_at
     and private.time_block_start(s.time_block) is not null
     and private.time_block_end(s.time_block) is not null
$$;

revoke all on function private.attendance_sessions(uuid, date) from public, anon, authenticated;

-- ─── 5. 학생이 찍는다: 입실 · 퇴실 ─────────────────────────────────────────
-- 돌려주는 action: check_in · check_out · already_in · already_done · too_early · class_over ·
--                  no_class_today · live_student · recorded_day · not_started · bad_token · too_many · login_required
create or replace function public.attendance_scan(p_token text, p_method text default 'qr')
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid    uuid := (select auth.uid());
  v_now    timestamptz := now();
  v_kst    timestamp := now() at time zone 'Asia/Seoul';
  v_today  date := private.today_kst();
  v_step   bigint := floor(extract(epoch from now()) / 30)::bigint;
  v_in     text := upper(regexp_replace(coalesce(p_token, ''), '[^0-9A-Za-z]', '', 'g'));
  v_method text := case when p_method = 'code' then 'code' else 'qr' end;
  v_open   record;
  v_target record;
  v_next   timestamp;
  v_label  text;
  v_stay   int;
  v_id     bigint;
  v_late   boolean;
begin
  if v_uid is null then
    return jsonb_build_object('action', 'login_required');
  end if;

  -- 틀린 코드를 10분에 10번 넣으면 잠시 막는다 (6자리를 맞혀 보는 것을 막는다)
  if (select count(*) from public.attendance_events ev
       where ev.student_id = v_uid and ev.kind = 'reject' and ev.result = 'bad_token' and ev.created_at > v_now - interval '10 minutes') >= 10 then
    return jsonb_build_object('action', 'too_many');
  end if;

  -- 지금 칸과 앞 세 칸(2분)만 — 로그인을 거치는 동안 한두 번 바뀌어도 된다
  if v_in = '' or not exists (
    select 1
      from generate_series(v_step - 3, v_step) as g(step)
      cross join lateral private.attendance_token(g.step) t
     where t.token = v_in or t.code = v_in
  ) then
    insert into public.attendance_events (student_id, kind, method, result) values (v_uid, 'reject', v_method, 'bad_token');
    return jsonb_build_object('action', 'bad_token');
  end if;

  -- 오늘 교실에 올 반이 없으면 왜 없는지 알려 준다
  if not exists (select 1 from private.attendance_sessions(v_uid, v_today)) then
    return jsonb_build_object('action',
      case
        when exists (
          select 1 from public.enrollments e
            join public.enrollment_orders o on o.id = e.order_id
            join public.session_dates d on d.section_id = e.section_id and d.date = v_today
           where e.student_id = v_uid and e.status = 'active' and o.status = 'active' and e.mode = 'live') then 'live_student'
        when exists (
          select 1 from public.enrollments e
            join public.enrollment_orders o on o.id = e.order_id
            join public.class_sections s on s.id = e.section_id
            join public.session_dates d on d.section_id = s.id and d.date = v_today
           where e.student_id = v_uid and e.status = 'active' and o.status = 'active' and s.recorded) then 'recorded_day'
        when exists (select 1 from public.enrollment_orders o where o.user_id = v_uid and o.status = 'preliminary') then 'not_started'
        else 'no_class_today'
      end);
  end if;

  -- ① 퇴실: 오늘 입실만 한 기록 — 그 반 수업이 끝나고 30분까지
  select st.id, st.section_id, st.check_in_at, x.label
    into v_open
    from public.attendance_stamps st
    join private.attendance_sessions(v_uid, v_today) x on x.section_id = st.section_id
   where st.student_id = v_uid
     and st.class_date = v_today
     and st.status = 'in'
     and v_kst <= x.ends + interval '30 minutes'
   order by st.check_in_at desc
   limit 1;
  if found then
    v_stay := floor(extract(epoch from (v_now - v_open.check_in_at)) / 60)::int;
    if v_stay < 30 then
      return jsonb_build_object('action', 'already_in', 'label', v_open.label,
                                'at', to_char(v_open.check_in_at at time zone 'Asia/Seoul', 'HH24:MI'), 'stay', v_stay);
    end if;
    update public.attendance_stamps
       set status = 'out', check_out_at = v_now, updated_at = v_now
     where id = v_open.id and status = 'in';
    if not found then
      return jsonb_build_object('action', 'already_done', 'label', v_open.label);
    end if;
    insert into public.attendance_events (student_id, section_id, class_date, kind, method, result)
    values (v_uid, v_open.section_id, v_today, 'exit', v_method, 'check_out');
    return jsonb_build_object('action', 'check_out', 'label', v_open.label, 'at', to_char(v_kst, 'HH24:MI'), 'stay', v_stay);
  end if;

  -- ② 입실: 수업 시작 30분 전 ~ 끝, 아직 도장이 없는 반 중 가장 이른 것
  select x.section_id, x.label, x.starts, x.ends
    into v_target
    from private.attendance_sessions(v_uid, v_today) x
   where v_kst between x.starts - interval '30 minutes' and x.ends
     and not exists (
       select 1 from public.attendance_stamps st
        where st.student_id = v_uid and st.section_id = x.section_id and st.class_date = v_today)
   order by x.starts
   limit 1;
  if not found then
    select x.label into v_label
      from private.attendance_sessions(v_uid, v_today) x
      join public.attendance_stamps st on st.student_id = v_uid and st.section_id = x.section_id and st.class_date = v_today
     where v_kst between x.starts - interval '30 minutes' and x.ends + interval '30 minutes'
     limit 1;
    if v_label is not null then
      return jsonb_build_object('action', 'already_done', 'label', v_label);
    end if;
    select min(x.starts) into v_next
      from private.attendance_sessions(v_uid, v_today) x
     where x.starts - interval '30 minutes' > v_kst;
    if v_next is not null then
      return jsonb_build_object('action', 'too_early', 'opens', to_char(v_next - interval '30 minutes', 'HH24:MI'));
    end if;
    return jsonb_build_object('action', 'class_over');
  end if;

  v_late := v_kst > v_target.starts + interval '7 minutes';
  insert into public.attendance_stamps (student_id, section_id, class_date, status, check_in_at, late, method)
  values (v_uid, v_target.section_id, v_today, 'in', v_now, v_late, v_method)
  on conflict (student_id, section_id, class_date) do nothing
  returning id into v_id;
  if v_id is null then
    return jsonb_build_object('action', 'already_done', 'label', v_target.label);
  end if;
  insert into public.attendance_events (student_id, section_id, class_date, kind, method, result)
  values (v_uid, v_target.section_id, v_today, 'enter', v_method, case when v_late then 'late' else 'check_in' end);

  return jsonb_build_object('action', 'check_in', 'label', v_target.label, 'at', to_char(v_kst, 'HH24:MI'),
                            'late', v_late, 'starts', to_char(v_target.starts, 'HH24:MI'), 'ends', to_char(v_target.ends, 'HH24:MI'));
end;
$$;

comment on function public.attendance_scan(text, text) is
  'QR·코드로 입실/퇴실. 토큰(2분)·배정·시각을 서버가 판정한다. 규칙: 시작 30분 전부터, 7분 뒤 지각, 30분 뒤부터 퇴실, 끝나고 30분까지';

-- ─── 6. 강사·조교가 정한다: 출석 인정 · 결석 · 되돌리기 ─────────────────────
create or replace function public.attendance_set(p_student uuid, p_section bigint, p_date date, p_status text, p_note text)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_note text := nullif(btrim(coalesce(p_note, '')), '');
begin
  if not private.is_crew() then
    raise exception 'forbidden';
  end if;
  if p_status not in ('manual', 'absent', 'clear') then
    raise exception 'bad_status';
  end if;
  -- 사유는 꼭 적는다 (나중에 "찍혔다가 사라졌다" 를 가릴 근거 — 첫토익 15)
  if p_status <> 'clear' and (v_note is null or char_length(v_note) > 200) then
    raise exception 'note_required';
  end if;
  if not exists (select 1 from public.enrollments e where e.student_id = p_student and e.section_id = p_section)
     or not exists (select 1 from public.session_dates d where d.section_id = p_section and d.date = p_date) then
    raise exception 'not_in_section';
  end if;

  if p_status = 'clear' then
    delete from public.attendance_stamps where student_id = p_student and section_id = p_section and class_date = p_date;
  else
    insert into public.attendance_stamps (student_id, section_id, class_date, status, method, late, decided_by, decided_note)
    values (p_student, p_section, p_date, p_status, 'manual', false, (select auth.uid()), v_note)
    on conflict (student_id, section_id, class_date) do update
       set status       = excluded.status,
           late         = false,   -- 출석 인정·결석은 지각 표시를 지운다
           decided_by   = excluded.decided_by,
           decided_note = excluded.decided_note,
           updated_at   = now();
  end if;

  insert into public.attendance_events (student_id, section_id, class_date, kind, method, result, actor_id, note)
  values (p_student, p_section, p_date, 'manual', 'manual', p_status, (select auth.uid()), v_note);
  return true;
end;
$$;

-- ─── 7. 날짜별 명단 (강사·관리자·조교) ─────────────────────────────────────
create or replace function public.attendance_roster(p_date date)
returns table (
  section_id bigint, course_name text, target_score int, track text, time_block text,
  student_id uuid, student_name text, phone text, tester boolean,
  status text, check_in_at timestamptz, check_out_at timestamptz, late boolean, decided_note text, decided_by_name text
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
  if not private.is_crew() then
    raise exception 'forbidden';
  end if;
  return query
  select s.id, c.name, c.target_score, s.track, s.time_block,
         p.id, p.name, p.phone,
         (p.test_role is not null or p.role in ('instructor', 'admin', 'assistant')),
         st.status, st.check_in_at, st.check_out_at, coalesce(st.late, false), st.decided_note, dp.name
    from public.session_dates d
    join public.class_sections s on s.id = d.section_id
    join public.courses c on c.id = s.course_id
    join public.enrollments e on e.section_id = s.id and e.status = 'active' and e.mode = 'onsite'
    join public.enrollment_orders o on o.id = e.order_id
     and o.status in ('active', 'expired') and o.activates_on <= p_date and p_date <= o.access_until
    join public.profiles p on p.id = e.student_id
    left join public.attendance_stamps st on st.student_id = p.id and st.section_id = s.id and st.class_date = p_date
    left join public.profiles dp on dp.id = st.decided_by
   where d.date = p_date
     and not s.recorded
   order by s.time_block, c.target_score, s.track, p.name;
end;
$$;

revoke all on function public.attendance_display() from public, anon;
revoke all on function public.attendance_scan(text, text) from public, anon;
revoke all on function public.attendance_set(uuid, bigint, date, text, text) from public, anon;
revoke all on function public.attendance_roster(date) from public, anon;
grant execute on function public.attendance_display() to authenticated;
grant execute on function public.attendance_scan(text, text) to authenticated;
grant execute on function public.attendance_set(uuid, bigint, date, text, text) to authenticated;
grant execute on function public.attendance_roster(date) to authenticated;

-- ─── 8. 계정 합치기가 출석도 옮긴다 (도메인 규칙 3-1 "기록은 남길 계정으로 모두") ───
-- 함께 고친 것: 교재주문은 "한 달 한 건" (unique user_id, term_id) 이라 두 계정이 같은 달 주문을 각각 갖고 있으면
-- 옮기는 순간 막혀 합치기가 통째로 실패한다 (20260921110500). 겹치는 쪽은 term_id 를 비워 기록을 그대로 두고 옮긴다.
create or replace function private.merge_accounts(p_from uuid, p_to uuid)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v jsonb := '{}'::jsonb;
  n int;
begin
  if p_from = p_to then
    raise exception 'same_account' using errcode = '22023';
  end if;
  if exists (select 1 from public.profiles p where p.id in (p_from, p_to) and (p.merged_into is not null or p.role in ('instructor', 'admin'))) then
    raise exception 'not_mergeable' using errcode = '22023';
  end if;

  delete from public.enrollments e
   where e.student_id = p_from
     and exists (select 1 from public.enrollments t where t.student_id = p_to and t.section_id = e.section_id);
  update public.enrollments set student_id = p_to where student_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('enrollments', n);

  update public.enrollment_orders set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('enrollment_orders', n);

  update public.enrollment_verifications set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('verifications', n);

  update public.homework_submissions set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('homework', n);

  delete from public.study_signups s
   where s.user_id = p_from
     and exists (select 1 from public.study_signups t where t.user_id = p_to and t.study_id = s.study_id);
  update public.study_signups set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('study_signups', n);

  -- 비대면 스터디 인증: 남길 계정에 같은 자료 인증이 있으면 지우고, 없으면 옮긴다
  delete from public.study_checkins c
   where c.user_id = p_from
     and exists (select 1 from public.study_checkins t where t.user_id = p_to and t.material_id = c.material_id);
  update public.study_checkins set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('study_checkins', n);

  delete from public.lecture_signups l
   where l.user_id = p_from
     and exists (select 1 from public.lecture_signups t where t.user_id = p_to and t.lecture_id = l.lecture_id);
  update public.lecture_signups set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('lecture_signups', n);

  -- 교재주문: 같은 달 주문이 둘이면 옮겨 오는 쪽의 달을 비운다 (입금·발송 기록은 그대로 남는다)
  update public.textbook_orders f
     set term_id = null
   where f.user_id = p_from
     and f.term_id is not null
     and f.status <> 'cancelled'
     and exists (select 1 from public.textbook_orders t where t.user_id = p_to and t.term_id = f.term_id and t.status <> 'cancelled');
  update public.textbook_orders set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('textbook_orders', n);

  update public.contact_messages set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('contacts', n);

  -- 알림함도 따라간다
  update public.student_messages set user_id = p_to where user_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('messages', n);

  -- 출석: 남길 계정에 같은 반·같은 날 도장이 있으면 그것을 남기고, 없으면 옮긴다. 기록은 전부 옮긴다
  delete from public.attendance_stamps a
   where a.student_id = p_from
     and exists (select 1 from public.attendance_stamps t where t.student_id = p_to and t.section_id = a.section_id and t.class_date = a.class_date);
  update public.attendance_stamps set student_id = p_to where student_id = p_from;
  get diagnostics n = row_count; v := v || jsonb_build_object('attendance', n);
  update public.attendance_events set student_id = p_to where student_id = p_from;

  update public.profiles p
     set role = 'student'
   where p.id = p_to
     and p.role in ('member', 'alumni')
     and exists (select 1 from public.enrollment_orders o where o.user_id = p_to and o.status = 'active');

  update public.profiles
     set merged_into = p_to
   where id = p_from;

  return v;
end;
$$;

revoke all on function private.merge_accounts(uuid, uuid) from public, anon, authenticated;
