-- ============================================================================
-- 반 편성 달력 (2026-09-15 Alan 요청)
--
--  * 반 편성은 기수(월) 달력에서 한다. 강사가 [개강일][종강일][월수금][화목금][특강] 버튼을 고르고
--    날짜를 하나씩 눌러 찍은 뒤 "생성하기" → public.save_term_schedule() 한 번(한 트랜잭션)에 저장된다.
--  * 기수 단위 원천
--      terms.enrollment_opens_at / closes_at — 그 달 개강일·종강일 (그 달 모든 반에 공통)
--      term_class_dates                      — 그 달 월수금 / 화목금 수업일. 한 날짜는 한 트랙에만
--      special_lectures                      — 특강. 수업일과 같은 날이어도 되고 하루에 여러 개도 된다
--      lecturers                             — 특강 강사 선택지 (이혜영 · 이영수). 행을 추가하면 늘어난다
--  * 반(class_sections)의 개강일·종강일·session_dates 는 기수 달력에서 파생된다.
--    생성하기와 반 개설 때 private.sync_section_schedule() 이 맞춘다.
--    다시보기가 붙은 회차를 빼야 하면 저장 전체를 되돌린다 (미확정 4 확정 전까지 녹화본 보호).
--  * 반 편성 화면에서 수업 시작·종료 시간을 받지 않는다 → 시간 컬럼을 nullable 로 바꾼다.
--    컬럼은 지우지 않는다 (배포 중인 main 코드가 아직 읽는다).
-- ============================================================================

-- ─── 1. 기수: 개강일 · 종강일 ───────────────────────────────────────────────
alter table public.terms
  add column enrollment_opens_at date,
  add column closes_at date,
  add constraint terms_closes_after_opens check (closes_at >= enrollment_opens_at);
comment on column public.terms.enrollment_opens_at is '그 달 개강일. 반 편성 달력에서 정하고 그 달 모든 반에 복사된다';
comment on column public.terms.closes_at is '그 달 종강일. 이 날이 지나면 다시보기가 닫힌다. 그 달 모든 반에 복사된다';

-- ─── 2. 수업 시간은 받지 않는다 ────────────────────────────────────────────
alter table public.class_sections
  alter column start_time drop not null,
  alter column end_time drop not null;
alter table public.session_dates
  alter column start_time drop not null,
  alter column end_time drop not null;

-- ─── 3. 기수 수업일 ────────────────────────────────────────────────────────
create table public.term_class_dates (
  term_id  bigint not null references public.terms (id) on delete cascade,
  date     date not null,
  track    text not null check (track in ('mwf', 'ttf')),
  primary key (term_id, date)
);
comment on table public.term_class_dates is '기수(월) 수업일. 한 날짜는 월수금·화목금 중 한 트랙에만 속한다. 반의 session_dates 는 여기서 파생된다';

-- ─── 4. 특강 강사 · 특강 ────────────────────────────────────────────────────
create table public.lecturers (
  id          bigint generated by default as identity primary key,
  name        text not null unique check (char_length(name) between 1 and 20),
  sort_order  int not null default 0
);
comment on table public.lecturers is '강사 명단 — 특강 강사 선택지. 로그인 계정(profiles)과 별개이며 행을 추가하면 선택지가 늘어난다';

insert into public.lecturers (name, sort_order) values ('이혜영', 1), ('이영수', 2);

create table public.special_lectures (
  id           bigint generated by default as identity primary key,
  term_id      bigint not null references public.terms (id) on delete cascade,
  date         date not null,
  lecturer_id  bigint not null references public.lecturers (id),
  content      text not null check (content = btrim(content) and char_length(content) between 1 and 100),
  created_at   timestamptz not null default now()
);
create index special_lectures_term_date_idx on public.special_lectures (term_id, date);
create index special_lectures_lecturer_id_idx on public.special_lectures (lecturer_id);
comment on table public.special_lectures is '특강. 수업일과 같은 날이어도 되고 하루에 여러 개도 된다';

-- ─── 5. grant + RLS ────────────────────────────────────────────────────────
grant all on public.term_class_dates, public.lecturers, public.special_lectures to service_role;
grant select on public.lecturers to authenticated;
grant select, insert, delete on public.term_class_dates, public.special_lectures to authenticated;
grant usage, select on all sequences in schema public to authenticated;

alter table public.term_class_dates enable row level security;
alter table public.lecturers        enable row level security;
alter table public.special_lectures enable row level security;

create policy "lecturers: 회원 조회" on public.lecturers
  for select to authenticated using (true);

create policy "term_class_dates: 스태프 조회" on public.term_class_dates
  for select to authenticated using ((select private.is_staff()));
create policy "term_class_dates: 스태프 등록" on public.term_class_dates
  for insert to authenticated with check ((select private.is_staff()));
create policy "term_class_dates: 스태프 삭제" on public.term_class_dates
  for delete to authenticated using ((select private.is_staff()));

create policy "special_lectures: 스태프 조회" on public.special_lectures
  for select to authenticated using ((select private.is_staff()));
create policy "special_lectures: 스태프 등록" on public.special_lectures
  for insert to authenticated with check ((select private.is_staff()));
create policy "special_lectures: 스태프 삭제" on public.special_lectures
  for delete to authenticated using ((select private.is_staff()));

-- ─── 6. 반 하나를 기수 달력에 맞춘다 ───────────────────────────────────────
-- 개강일·종강일·수업일(session_dates)·회차 수를 맞추고, 이 반에 배정된 등록의
-- 활성화일·시청 만료일도 배정된 반들의 개강일·종강일로 갱신한다.
create or replace function private.sync_section_schedule(p_section_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_term_id  bigint;
  v_track    text;
  v_opens    date;
  v_closes   date;
  v_blocked  text;
  v_count    int;
begin
  select s.term_id, s.track, t.enrollment_opens_at, t.closes_at
    into v_term_id, v_track, v_opens, v_closes
  from public.class_sections s
  join public.terms t on t.id = s.term_id
  where s.id = p_section_id;
  if not found then
    return;
  end if;

  -- 1) 빠질 회차에 다시보기가 붙어 있으면 막는다
  select string_agg(to_char(sd.date, 'YYYY-MM-DD'), ',' order by sd.date)
    into v_blocked
  from public.session_dates sd
  where sd.section_id = p_section_id
    and not exists (
      select 1 from public.term_class_dates d
      where d.term_id = v_term_id and d.track = v_track and d.date = sd.date
    )
    and exists (select 1 from public.replays r where r.session_date_id = sd.id);
  if v_blocked is not null then
    raise exception 'replay_block' using errcode = 'P0001', detail = v_blocked;
  end if;

  -- 2) 달력에서 빠진 날짜 삭제
  delete from public.session_dates sd
  where sd.section_id = p_section_id
    and not exists (
      select 1 from public.term_class_dates d
      where d.term_id = v_term_id and d.track = v_track and d.date = sd.date
    );

  -- 3) 새 날짜 추가 (임시 회차 번호 — 아래에서 날짜순으로 다시 매긴다)
  insert into public.session_dates (section_id, seq, date)
  select p_section_id, 100000 + row_number() over (order by d.date), d.date
  from public.term_class_dates d
  where d.term_id = v_term_id
    and d.track = v_track
    and not exists (
      select 1 from public.session_dates sd
      where sd.section_id = p_section_id and sd.date = d.date
    );

  -- 4) 회차 번호를 날짜순 1..n 으로. unique(section_id, seq) 충돌을 피하려고 먼저 비켜 둔다
  update public.session_dates set seq = seq + 200000 where section_id = p_section_id;
  update public.session_dates sd
  set seq = o.rn
  from (
    select id, row_number() over (order by date) as rn
    from public.session_dates
    where section_id = p_section_id
  ) o
  where sd.id = o.id;

  -- 5) 반의 개강일·종강일·회차 수
  select count(*) into v_count from public.session_dates where section_id = p_section_id;
  update public.class_sections s
  set enrollment_opens_at = coalesce(v_opens, s.enrollment_opens_at),
      closes_at           = coalesce(v_closes, s.closes_at),
      target_sessions     = case when v_count > 0 then v_count else s.target_sessions end
  where s.id = p_section_id
    and (s.enrollment_opens_at, s.closes_at, s.target_sessions) is distinct from
        (coalesce(v_opens, s.enrollment_opens_at), coalesce(v_closes, s.closes_at),
         case when v_count > 0 then v_count else s.target_sessions end);

  -- 6) 이 반이 들어간 등록: 활성화일 = 배정된 반 중 가장 이른 개강일, 만료일 = 가장 늦은 종강일
  update public.enrollment_orders o
  set activates_on = m.min_opens,
      access_until = m.max_closes
  from (
    select e.order_id, min(s.enrollment_opens_at) as min_opens, max(s.closes_at) as max_closes
    from public.enrollments e
    join public.class_sections s on s.id = e.section_id
    where e.order_id in (select e2.order_id from public.enrollments e2 where e2.section_id = p_section_id)
    group by e.order_id
  ) m
  where o.id = m.order_id
    and o.status in ('preliminary', 'active')
    and (o.activates_on, o.access_until) is distinct from (m.min_opens, m.max_closes);
end;
$$;

-- 기수의 모든 반을 달력에 맞춘다 (save_term_schedule 이 호출)
create or replace function private.sync_term_sections(p_term_id bigint)
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id  bigint;
  v_n   int := 0;
begin
  if not private.is_staff() then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  for v_id in select id from public.class_sections where term_id = p_term_id order by id loop
    perform private.sync_section_schedule(v_id);
    v_n := v_n + 1;
  end loop;
  return v_n;
end;
$$;

-- 반을 개설하면 그 달 개강일·종강일을 채우고(before), 수업일을 만든다(after)
create or replace function private.trg_class_sections_fill_schedule()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_opens   date;
  v_closes  date;
begin
  select t.enrollment_opens_at, t.closes_at into v_opens, v_closes
  from public.terms t
  where t.id = new.term_id;
  if v_opens is not null and v_closes is not null then
    new.enrollment_opens_at := v_opens;
    new.closes_at := v_closes;
  end if;
  return new;
end;
$$;

create trigger class_sections_fill_schedule
  before insert or update of term_id on public.class_sections
  for each row execute function private.trg_class_sections_fill_schedule();

create or replace function private.trg_class_sections_sync_schedule()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.sync_section_schedule(new.id);
  return null;
end;
$$;

create trigger class_sections_sync_schedule
  after insert or update of term_id, track on public.class_sections
  for each row execute function private.trg_class_sections_sync_schedule();

-- ─── 7. 생성하기: 기수 달력 저장 ────────────────────────────────────────────
-- security invoker — terms · term_class_dates · special_lectures 쓰기는 스태프 RLS 를 그대로 받는다.
-- 여러 강사의 반을 한꺼번에 맞추는 부분만 private.sync_term_sections (definer) 가 한다.
-- p_lectures: [{"date": "YYYY-MM-DD", "lecturer_id": 1, "content": "..."}]
create or replace function public.save_term_schedule(
  p_year      int,
  p_month     int,
  p_opens     date,
  p_closes    date,
  p_mwf       date[],
  p_ttf       date[],
  p_lectures  jsonb
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_term_id   bigint;
  v_first     date;
  v_last      date;
  v_mwf       date[] := coalesce(p_mwf, '{}');
  v_ttf       date[] := coalesce(p_ttf, '{}');
  v_lectures  jsonb := coalesce(p_lectures, '[]'::jsonb);
  v_bad       text;
  v_sections  int;
begin
  if not (select private.is_staff()) then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if p_year is null or p_month is null or p_year not between 2020 and 2100 or p_month not between 1 and 12 then
    raise exception 'invalid_term' using errcode = '22023';
  end if;
  if p_opens is null or p_closes is null then
    raise exception 'dates_required' using errcode = '22023';
  end if;
  if p_closes < p_opens then
    raise exception 'closes_before_opens' using errcode = '22023';
  end if;

  v_first := make_date(p_year, p_month, 1);
  v_last  := (v_first + interval '1 month')::date - 1;

  -- 수업일: 그 달 안에서만, 한 날짜는 한 트랙만
  if exists (select 1 from unnest(v_mwf || v_ttf) as d where d is null or d < v_first or d > v_last) then
    raise exception 'class_date_out_of_month' using errcode = '22023';
  end if;
  select string_agg(to_char(x.d, 'YYYY-MM-DD'), ',' order by x.d) into v_bad
  from (select unnest(v_mwf) as d intersect select unnest(v_ttf)) as x;
  if v_bad is not null then
    raise exception 'track_overlap' using errcode = '22023', detail = v_bad;
  end if;

  -- 특강: 그 달 안, 강사 지정, 내용 1~100자
  if jsonb_typeof(v_lectures) <> 'array' or jsonb_array_length(v_lectures) > 100 then
    raise exception 'invalid_lectures' using errcode = '22023';
  end if;
  if exists (
    select 1
    from jsonb_array_elements(v_lectures) as e
    where jsonb_typeof(e) <> 'object'
       or e ->> 'date' is null
       or e ->> 'lecturer_id' is null
       or (e ->> 'date')::date not between v_first and v_last
       or char_length(btrim(coalesce(e ->> 'content', ''))) not between 1 and 100
  ) then
    raise exception 'invalid_lectures' using errcode = '22023';
  end if;

  insert into public.terms (year, month) values (p_year, p_month)
  on conflict (year, month) do nothing;
  select t.id into v_term_id from public.terms t where t.year = p_year and t.month = p_month;

  update public.terms
  set enrollment_opens_at = p_opens,
      closes_at = p_closes
  where id = v_term_id;

  delete from public.term_class_dates where term_id = v_term_id;
  insert into public.term_class_dates (term_id, date, track)
  select v_term_id, m.d, 'mwf' from (select distinct unnest(v_mwf) as d) as m
  union all
  select v_term_id, t.d, 'ttf' from (select distinct unnest(v_ttf) as d) as t;

  delete from public.special_lectures where term_id = v_term_id;
  insert into public.special_lectures (term_id, date, lecturer_id, content)
  select v_term_id, (l.e ->> 'date')::date, (l.e ->> 'lecturer_id')::bigint, btrim(l.e ->> 'content')
  from jsonb_array_elements(v_lectures) with ordinality as l(e, ord)
  order by l.ord;

  v_sections := private.sync_term_sections(v_term_id);

  return jsonb_build_object(
    'term_id',  v_term_id,
    'mwf',      (select count(*) from public.term_class_dates where term_id = v_term_id and track = 'mwf'),
    'ttf',      (select count(*) from public.term_class_dates where term_id = v_term_id and track = 'ttf'),
    'lectures', (select count(*) from public.special_lectures where term_id = v_term_id),
    'sections', v_sections
  );
end;
$$;

-- ─── 8. 함수 실행 권한 ─────────────────────────────────────────────────────
revoke all on function public.save_term_schedule(int, int, date, date, date[], date[], jsonb) from public, anon;
grant execute on function public.save_term_schedule(int, int, date, date, date[], date[], jsonb) to authenticated, service_role;

revoke all on function
  private.sync_section_schedule(bigint),
  private.sync_term_sections(bigint),
  private.trg_class_sections_fill_schedule(),
  private.trg_class_sections_sync_schedule()
from public, anon, authenticated;
-- save_term_schedule(invoker) 가 로그인 사용자 권한으로 호출한다. 함수 안에서 스태프인지 다시 확인한다.
grant execute on function private.sync_term_sections(bigint) to authenticated, service_role;
