-- ============================================================================
-- 범위 확장 (2026-09-15 Alan 요청)
--
--  * 회원가입 시 마케팅 분석용 정보 수집: 대학, 학과, 성별
--  * 등록 방식 구분: 현장(onsite) / 불라방(live) → 시간대별 인원수 위젯 "현장 (불라방)"
--  * class_sections 에 불라방 수강료(live_tuition) 추가 — OCR 매칭 기준선 (금액은 미확정)
--  * 불라방 교재신청 (textbook_orders)
--  * 스터디 신청 (study_applications)
--  * 연락하기 (contact_messages)
-- ============================================================================

-- ─── 1. profiles: 마케팅 분석 필드 ──────────────────────────────────────────
alter table public.profiles
  add column university text,
  add column department text,
  add column gender text check (gender in ('male', 'female', 'other', 'undisclosed'));

-- 가입 트리거가 메타데이터에서 함께 채우도록 갱신
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, phone, university, department, gender)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), ''),
    nullif(trim(new.raw_user_meta_data ->> 'phone'), ''),
    nullif(trim(new.raw_user_meta_data ->> 'university'), ''),
    nullif(trim(new.raw_user_meta_data ->> 'department'), ''),
    case
      when new.raw_user_meta_data ->> 'gender' in ('male', 'female', 'other', 'undisclosed')
        then new.raw_user_meta_data ->> 'gender'
      else null
    end
  );
  return new;
end;
$$;

-- 본인 수정 정책: 전화번호 외에 대학·학과·성별도 본인이 고칠 수 있게 한다 (name/role 은 여전히 잠금)
drop policy "profiles: 본인(전화번호만)·admin 수정" on public.profiles;
grant update (name, phone, role, university, department, gender) on public.profiles to authenticated;
create policy "profiles: 본인·admin 수정" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id or (select private.is_admin()))
  with check (
    (select private.is_admin())
    or (
      (select auth.uid()) = id
      and role = (select private.user_role())
      and name = (select p.name from public.profiles p where p.id = (select auth.uid()))
    )
  );

-- ─── 2. 현장 / 불라방 구분 ──────────────────────────────────────────────────
alter table public.class_sections
  add column live_tuition int check (live_tuition is null or live_tuition >= 0);
comment on column public.class_sections.live_tuition is '불라방 수강료. null 이면 이 반은 불라방 미운영';

alter table public.enrollments
  add column mode text not null default 'onsite' check (mode in ('onsite', 'live'));
comment on column public.enrollments.mode is 'onsite = 현장 수강, live = 불라방';

-- ─── 3. 불라방 교재신청 ────────────────────────────────────────────────────
-- 불라방 수강생은 현장에서 교재를 받을 수 없으므로 배송 신청을 받는다. 결제는 이 사이트에서 하지 않는다.
create table public.textbook_orders (
  id              bigint generated by default as identity primary key,
  user_id         uuid not null references public.profiles (id) on delete cascade,
  section_id      bigint not null references public.class_sections (id),
  recipient_name  text not null,
  phone           text not null,
  postal_code     text,
  address         text not null,
  address_detail  text,
  quantity        int not null default 1 check (quantity between 1 and 5),
  memo            text,
  status          text not null default 'requested'
                  check (status in ('requested', 'confirmed', 'shipped', 'cancelled')),
  tracking_no     text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index textbook_orders_user_id_idx on public.textbook_orders (user_id);
create index textbook_orders_section_id_idx on public.textbook_orders (section_id);
create index textbook_orders_status_created_idx on public.textbook_orders (status, created_at desc);

-- ─── 4. 스터디 신청 ────────────────────────────────────────────────────────
create table public.study_applications (
  id              bigint generated by default as identity primary key,
  user_id         uuid references public.profiles (id) on delete set null,   -- 비회원 신청 허용
  name            text not null,
  phone           text not null,
  target_score    int check (target_score is null or target_score between 10 and 990),
  preferred_time  text,                       -- 자유 입력 (예: 평일 저녁, 주말 오전)
  message         text,
  status          text not null default 'pending'
                  check (status in ('pending', 'contacted', 'confirmed', 'closed')),
  created_at      timestamptz not null default now()
);
create index study_applications_user_id_idx on public.study_applications (user_id);
create index study_applications_status_created_idx on public.study_applications (status, created_at desc);

-- ─── 5. 연락하기 ───────────────────────────────────────────────────────────
create table public.contact_messages (
  id          bigint generated by default as identity primary key,
  user_id     uuid references public.profiles (id) on delete set null,       -- 비회원 허용
  name        text not null,
  phone       text,
  email       text,
  message     text not null check (char_length(message) between 1 and 2000),
  status      text not null default 'new' check (status in ('new', 'read', 'replied')),
  created_at  timestamptz not null default now(),
  check (phone is not null or email is not null)
);
create index contact_messages_status_created_idx on public.contact_messages (status, created_at desc);

-- ─── 6. grant + RLS ────────────────────────────────────────────────────────
grant all on public.textbook_orders, public.study_applications, public.contact_messages to service_role;

-- textbook_orders: 불라방 수강생이 본인 반에 대해 신청. 본인 조회·취소, 스태프 전체 관리
grant select, insert, update on public.textbook_orders to authenticated;
alter table public.textbook_orders enable row level security;
create policy "textbook_orders: 본인·스태프 조회" on public.textbook_orders
  for select to authenticated
  using ((select auth.uid()) = user_id or (select private.is_staff()));
create policy "textbook_orders: 불라방 수강생 신청" on public.textbook_orders
  for insert to authenticated
  with check (
    (select auth.uid()) = user_id
    and status = 'requested'
    and exists (
      select 1 from public.enrollments e
      where e.student_id = (select auth.uid())
        and e.section_id = textbook_orders.section_id
        and e.status = 'active'
        and e.mode = 'live'
    )
  );
create policy "textbook_orders: 본인 취소·스태프 처리" on public.textbook_orders
  for update to authenticated
  using ((select auth.uid()) = user_id or (select private.is_staff()))
  with check (
    (select private.is_staff())
    or ((select auth.uid()) = user_id and status in ('requested', 'cancelled'))
  );

-- study_applications: 누구나 신청(anon 포함), 본인 조회, 스태프 전체 관리
grant insert on public.study_applications to anon;
grant select, insert, update on public.study_applications to authenticated;
alter table public.study_applications enable row level security;
create policy "study: 비회원 신청" on public.study_applications
  for insert to anon
  with check (user_id is null and status = 'pending');
create policy "study: 회원 신청" on public.study_applications
  for insert to authenticated
  with check (user_id = (select auth.uid()) and status = 'pending');
create policy "study: 본인·스태프 조회" on public.study_applications
  for select to authenticated
  using ((select auth.uid()) = user_id or (select private.is_staff()));
create policy "study: 스태프 처리" on public.study_applications
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

-- contact_messages: 누구나 남김, 스태프만 열람·처리 (본인 조회 불필요)
grant insert on public.contact_messages to anon;
grant select, insert, update on public.contact_messages to authenticated;
alter table public.contact_messages enable row level security;
create policy "contact: 비회원 문의" on public.contact_messages
  for insert to anon
  with check (user_id is null and status = 'new');
create policy "contact: 회원 문의" on public.contact_messages
  for insert to authenticated
  with check ((user_id is null or user_id = (select auth.uid())) and status = 'new');
create policy "contact: 스태프 조회" on public.contact_messages
  for select to authenticated
  using ((select private.is_staff()));
create policy "contact: 스태프 처리" on public.contact_messages
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

grant usage, select on all sequences in schema public to authenticated;
grant usage, select on all sequences in schema public to anon;   -- anon insert 에 identity 시퀀스 필요

-- ─── 7. 관리자 대시보드용 헬퍼 뷰 ──────────────────────────────────────────
-- 시간대별 인원수: 반(section) 단위로 현장 / 불라방 활성 수강생 수
create view public.section_headcounts
with (security_invoker = true) as
  select
    s.id as section_id,
    s.term_id,
    s.course_id,
    s.track,
    s.time_block,
    s.start_time,
    s.end_time,
    count(*) filter (where e.mode = 'onsite') as onsite_count,
    count(*) filter (where e.mode = 'live')   as live_count
  from public.class_sections s
  left join public.enrollments e
    on e.section_id = s.id and e.status = 'active'
  group by s.id;

grant select on public.section_headcounts to authenticated;
