-- ============================================================================
-- 수업자료실 — 레벨 × RC/LC (2026-10-05 Alan — "지금 수업자료실이 없어! 수업자료실을 하나 만들어야하는데, 레벨별 구분과 RC, LC가 구분되어야해.")
--
--   * 강사·관리자가 /admin/class-materials 에서 레벨(lc_levels — 650 · 750 · 850) × 과목(RC · LC)을 골라 파일을 올린다.
--     조교는 아니다 — 관리자 화면은 Alan 이 정한 여섯 가지만 연다 (CLAUDE.md 등급 체계 9-1).
--   * 학생(/my/materials)에게는 **내 레벨만** 열린다 — 화면이 아니라 DB 가 막는다 (LC 음원과 같은 규칙, 마이그레이션 20261003120000).
--     내 레벨 = private.my_lc_levels() — 지금 접근할 수 있는 반(개강일~종강일 · 120분 반이 품는 시간 · 속성반이 여는 반)의
--     강좌 레벨 + 속성반이 함께 듣는 레벨(650+ 중급속성 = 650 · 850). 화면(src/lib/lc-audio.ts 의 lcLevelsOf)과 같은 규칙이다.
--     내 레벨 안에서는 RC · LC 둘 다 열린다. 예비등록생(개강 전) · 졸업생(종강 뒤)에게는 열리지 않는다.
--   * 강사 · 관리자는 전부 본다 (관리자 화면). 테스트 등급을 켠 스태프는 그 등급의 학생으로 본다 (private.is_staff · user_role).
--   * 파일은 private 버킷 class-materials — 50MB, 형식 제한 없음 (비대면 자료와 같다 — 스태프만 올린다. pdf · hwp · docx · pptx · 그림 …).
--     저장소 조회는 **이 표의 행이 보이는지**로 판정한다 — 그래서 남의 레벨 파일은 서명 URL 도 만들 수 없다.
--   * 새 표 = RLS + 정책 + grant 를 이 파일 하나에 (CLAUDE.md 보안 점검).
-- ============================================================================

create table if not exists public.class_materials (
  id           bigint generated by default as identity primary key,
  level        int not null references public.lc_levels (level),
  subject      text not null check (subject in ('rc', 'lc')),
  title        text not null check (char_length(title) between 1 and 100),
  note         text check (note is null or char_length(note) <= 500),
  file_path    text not null unique,                 -- storage: class-materials/{level}-{subject}/…
  file_name    text not null,
  file_size    bigint check (file_size is null or file_size >= 0),
  content_type text,
  uploaded_by  uuid references public.profiles (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

comment on table public.class_materials is '수업자료실 — 레벨(lc_levels) × 과목(rc|lc) 자료 파일. 학생은 내 레벨만(private.my_lc_levels), 쓰기는 강사·관리자 (2026-10-05)';

create index if not exists class_materials_level_subject_idx on public.class_materials (level, subject, created_at desc);
create index if not exists class_materials_uploaded_by_idx on public.class_materials (uploaded_by);

alter table public.class_materials enable row level security;

grant select, insert, update, delete on public.class_materials to authenticated;
grant all on public.class_materials to service_role;

create policy "class_materials: 내 레벨 수강생·스태프 조회" on public.class_materials
  for select to authenticated
  using ((select private.is_staff()) or array[level] <@ (select private.my_lc_levels()));
create policy "class_materials: 스태프 등록" on public.class_materials
  for insert to authenticated with check ((select private.is_staff()));
create policy "class_materials: 스태프 수정" on public.class_materials
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "class_materials: 스태프 삭제" on public.class_materials
  for delete to authenticated using ((select private.is_staff()));

-- ─── 파일 저장소 (private) ──────────────────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('class-materials', 'class-materials', false, 50 * 1024 * 1024, null)
on conflict (id) do nothing;

-- 조회 = class_materials 행을 볼 수 있는 사람 (위 정책 — 학생은 내 레벨만). 쓰기는 강사·관리자
create policy "class-materials: 내 레벨 수강생·스태프 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'class-materials'
    and (
      (select private.is_staff())
      or exists (select 1 from public.class_materials m where m.file_path = objects.name)
    )
  );
create policy "class-materials: 스태프 업로드" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'class-materials' and (select private.is_staff()));
create policy "class-materials: 스태프 수정" on storage.objects
  for update to authenticated
  using (bucket_id = 'class-materials' and (select private.is_staff()))
  with check (bucket_id = 'class-materials' and (select private.is_staff()));
create policy "class-materials: 스태프 삭제" on storage.objects
  for delete to authenticated
  using (bucket_id = 'class-materials' and (select private.is_staff()));
