-- ============================================================================
-- 비대면 자료를 회차(1회차 · 2회차 …)로 — 한 번 올리면 매달 그 달 일정표에 따라 열린다 (2026-09-22 Alan)
--   "비대면 자료올리기는 1회차, 2회차... 이렇게 설정하고 매달 강사들이 설정한 일정표에 따라 적용되면 좋겠어."
--   Alan 이 고른 것: 자료는 **한 번 올리고 매달 재사용** · 회차 날짜는 **그 달 수업일 전체 순서**(월수금 + 화목금, 평일마다 하나).
--
--   * 새 표 `study_material_items` = 회차별 공통 자료실 (회차 하나에 파일 하나, 스태프만 본다).
--   * 기존 `study_materials` 는 이제 **그 달에 적용된 회차**다 — 강사가 직접 쓰지 않고 `private.sync_online_materials` 가 채운다:
--       그 달(기수) 수업일(term_class_dates, 개강일~종강일 안)을 날짜순으로 1, 2, 3 … → 같은 번호의 자료실 회차를 그 날짜에 둔다.
--     그래서 학생 쪽(날짜가 되면 공개 · 신청자 · 수강 중 — RLS 그대로) · 인증(study_checkins) · 강사 인증 현황은 바뀌지 않는다.
--   * 다시 맞추는 때: 자료실을 바꿀 때 · 강사가 반 편성 달력(수업일 · 개강일 · 종강일)을 바꿀 때 · 그 달 비대면스터디를 열 때.
--     끝난 달(종강일이 지난 기수)은 건드리지 않는다 — 지난 기록이다.
--   * **인증이 붙은 회차 행은 지우지 않는다** — study_checkins 가 on delete cascade 라 행을 지우면 학생 인증이 함께 사라진다.
--     그런 행은 날짜·파일만 새로 맞추고, 수업일이 줄어 번호가 사라졌으면 그대로 남긴다.
--   * 지금까지 올린 날짜별 자료는 0건이었다 (2026-09-22 확인) — 옮길 것이 없다.
-- ============================================================================

-- ─── 1. 회차별 공통 자료실 ──────────────────────────────────────────────────
create table if not exists public.study_material_items (
  id           bigint generated by default as identity primary key,
  seq          int not null unique check (seq between 1 and 60),
  title        text check (title is null or char_length(title) <= 100),
  file_path    text not null unique,                 -- storage: study-materials/items/…
  file_name    text not null,
  file_size    bigint check (file_size is null or file_size >= 0),
  content_type text,
  uploaded_by  uuid references public.profiles (id) on delete set null,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists study_material_items_uploaded_by_idx on public.study_material_items (uploaded_by);

alter table public.study_material_items enable row level security;
grant select, insert, update, delete on public.study_material_items to authenticated;
grant all on public.study_material_items to service_role;

create policy "study_material_items: 스태프 조회" on public.study_material_items
  for select to authenticated using ((select private.is_staff()));
create policy "study_material_items: 스태프 등록" on public.study_material_items
  for insert to authenticated with check ((select private.is_staff()));
create policy "study_material_items: 스태프 수정" on public.study_material_items
  for update to authenticated using ((select private.is_staff())) with check ((select private.is_staff()));
create policy "study_material_items: 스태프 삭제" on public.study_material_items
  for delete to authenticated using ((select private.is_staff()));

comment on table public.study_material_items is
  '비대면 자료 회차별 공통 자료실 (2026-09-22). 매달 그 달 수업일 순서로 study_materials 에 적용된다 — private.sync_online_materials';

-- ─── 2. 그 달에 적용된 회차 (study_materials) ─────────────────────────────
alter table public.study_materials add column if not exists seq int check (seq is null or seq between 1 and 60);
alter table public.study_materials add column if not exists item_id bigint references public.study_material_items (id) on delete set null;

-- 여러 달이 같은 파일을 쓰므로 파일 경로가 겹친다 · 날짜는 일정표를 따라 움직이므로 (기수, 회차) 가 한 칸이다
alter table public.study_materials drop constraint if exists study_materials_file_path_key;
alter table public.study_materials drop constraint if exists study_materials_study_id_date_key;
create unique index if not exists study_materials_study_seq_key on public.study_materials (study_id, seq);
create index if not exists study_materials_file_path_idx on public.study_materials (file_path);
create index if not exists study_materials_item_id_idx on public.study_materials (item_id);

-- 그 달(기수) 수업일 순서 = 회차. 월수금 + 화목금 합집합, 개강일~종강일이 있으면 그 안만
create or replace function private.term_class_days(p_term_id bigint)
returns table (seq int, date date)
language sql
stable
security definer
set search_path = ''
as $$
  select (row_number() over (order by d.date))::int, d.date
    from (
      select distinct c.date
        from public.term_class_dates c
        join public.terms t on t.id = c.term_id
       where c.term_id = p_term_id
         and (t.enrollment_opens_at is null or c.date >= t.enrollment_opens_at)
         and (t.closes_at is null or c.date <= t.closes_at)
    ) d
$$;

revoke all on function private.term_class_days(bigint) from public, anon, authenticated;

create or replace function private.sync_online_materials()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  r record;
begin
  for r in
    select s.id as study_id, s.term_id
      from public.studies s
      join public.terms t on t.id = s.term_id
     where s.kind = 'online'
       and (t.closes_at is null or t.closes_at >= private.today_kst())   -- 끝난 달은 지난 기록이다
  loop
    insert into public.study_materials as m
      (study_id, seq, date, item_id, title, file_path, file_name, file_size, content_type, uploaded_by, updated_at)
    select r.study_id, d.seq, d.date, i.id, i.title, i.file_path, i.file_name, i.file_size, i.content_type, i.uploaded_by, now()
      from private.term_class_days(r.term_id) d
      join public.study_material_items i on i.seq = d.seq
    on conflict (study_id, seq) do update
       set date = excluded.date, item_id = excluded.item_id, title = excluded.title, file_path = excluded.file_path,
           file_name = excluded.file_name, file_size = excluded.file_size, content_type = excluded.content_type,
           uploaded_by = excluded.uploaded_by, updated_at = now()
     where (m.date, m.item_id, m.title, m.file_path, m.file_name, m.file_size, m.content_type)
           is distinct from
           (excluded.date, excluded.item_id, excluded.title, excluded.file_path, excluded.file_name, excluded.file_size, excluded.content_type);

    -- 더는 없는 회차(수업일이 줄었거나 자료를 지웠다)는 뺀다 — 인증이 붙은 행은 남긴다 (지우면 인증이 함께 지워진다)
    delete from public.study_materials m
     where m.study_id = r.study_id
       and not exists (
         select 1
           from private.term_class_days(r.term_id) d
           join public.study_material_items i on i.seq = d.seq
          where d.seq = m.seq)
       and not exists (select 1 from public.study_checkins c where c.material_id = m.id);
  end loop;
end;
$$;

revoke all on function private.sync_online_materials() from public, anon, authenticated;

create or replace function private.tg_sync_online_materials()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform private.sync_online_materials();
  return null;
end;
$$;

-- 자료실을 바꿀 때 · 수업일을 바꿀 때 · 개강일·종강일을 바꿀 때 · 그 달 비대면스터디를 열 때
drop trigger if exists study_material_items_sync on public.study_material_items;
create trigger study_material_items_sync
  after insert or update or delete on public.study_material_items
  for each statement execute function private.tg_sync_online_materials();

drop trigger if exists term_class_dates_sync_materials on public.term_class_dates;
create trigger term_class_dates_sync_materials
  after insert or update or delete on public.term_class_dates
  for each statement execute function private.tg_sync_online_materials();

drop trigger if exists terms_sync_materials on public.terms;
create trigger terms_sync_materials
  after update of enrollment_opens_at, closes_at on public.terms
  for each statement execute function private.tg_sync_online_materials();

drop trigger if exists studies_sync_materials on public.studies;
create trigger studies_sync_materials
  after insert on public.studies
  for each statement execute function private.tg_sync_online_materials();
