-- ============================================================================
-- 역전토익 LMS — 초기 스키마
-- 출처: CLAUDE.md "데이터 모델" · "학생 등급" · "콘텐츠 접근" 규칙
--
-- 설계 메모
--  * 새 Supabase 프로젝트는 테이블을 만들어도 Data API에 자동 노출되지 않는다
--    (2026-04-28 변경). 따라서 테이블마다 grant + RLS + policy 를 한 세트로 둔다.
--  * 헬퍼 함수는 API에 노출되지 않는 private 스키마에 둔다.
--  * "오늘"은 항상 한국 시간 기준 (private.today_kst). DB 세션 타임존은 UTC 이므로
--    current_date 를 직접 쓰면 개강·종강 전환이 오전 9시에 일어난다.
--  * live_url 은 수강생 전용이므로 공개 시간표는 별도 뷰(class_sections_public)로 노출한다.
-- ============================================================================

-- ─── 0. private 스키마 ──────────────────────────────────────────────────────
create schema if not exists private;
revoke all on schema private from public;
grant usage on schema private to authenticated, service_role;

create or replace function private.today_kst()
returns date
language sql
stable
set search_path = ''
as $$
  select (now() at time zone 'Asia/Seoul')::date
$$;

-- ─── 1. 열거형 ──────────────────────────────────────────────────────────────
create type public.user_role as enum
  ('guest', 'member', 'student', 'alumni', 'instructor', 'admin');

-- ─── 2. 테이블 ──────────────────────────────────────────────────────────────

-- 회원 프로필. auth.users 와 1:1
create table public.profiles (
  id          uuid primary key references auth.users (id) on delete cascade,
  name        text not null,                        -- 실명. 수강증 대조(G3)에 사용
  phone       text,
  role        public.user_role not null default 'member',
  created_at  timestamptz not null default now()
);
comment on table public.profiles is '회원 프로필. name 은 수강증 수강생명과 대조하므로 본인이 임의 수정 불가';

-- 기수 = 월
create table public.terms (
  id     bigint generated by default as identity primary key,
  year   int not null check (year between 2020 and 2100),
  month  int not null check (month between 1 and 12),
  unique (year, month)
);

-- 강좌 마스터
create table public.courses (
  id            bigint generated by default as identity primary key,
  code          text not null unique,
  name          text not null,
  course_type   text not null check (course_type in ('full', 'lc', 'rc')),
  target_score  int,
  is_active     boolean not null default true
);

-- 트랙 단위 분반 (주5일반 = MWF + TTF 두 행, bundle_id 로 묶음)
create table public.class_sections (
  id                   bigint generated by default as identity primary key,
  course_id            bigint not null references public.courses (id),
  term_id              bigint not null references public.terms (id),
  bundle_id            uuid,
  track                text not null check (track in ('mwf', 'ttf')),
  start_time           time not null,
  end_time             time not null,
  time_block           text,                        -- 시간대 라벨. Alan 확정 후 입력 (미확정 1)
  enrollment_opens_at  date not null,               -- 개강일: 수강증 업로드 개시
  closes_at            date not null,               -- 종강일: 다시보기 차단
  target_sessions      int not null check (target_sessions > 0),
  instructor_id        uuid references public.profiles (id),
  capacity             int check (capacity is null or capacity > 0),
  tuition              int not null check (tuition >= 0),  -- OCR 매칭 기준선 (미확정 2)
  live_url             text,                        -- 불라방 입장 링크. 수강생 전용
  status               text not null default 'open'
                       check (status in ('draft', 'open', 'closed')),
  created_at           timestamptz not null default now(),
  check (end_time > start_time),
  check (closes_at >= enrollment_opens_at)
);
create index class_sections_course_id_idx     on public.class_sections (course_id);
create index class_sections_term_id_idx       on public.class_sections (term_id);
create index class_sections_instructor_id_idx on public.class_sections (instructor_id);
create index class_sections_bundle_id_idx     on public.class_sections (bundle_id) where bundle_id is not null;

-- 진실의 원천. 강사가 캘린더에서 확정한 실제 수업 날짜
create table public.session_dates (
  id          bigint generated by default as identity primary key,
  section_id  bigint not null references public.class_sections (id) on delete cascade,
  seq         int not null check (seq > 0),
  date        date not null,
  start_time  time not null,
  end_time    time not null,
  unique (section_id, seq),
  unique (section_id, date),
  check (end_time > start_time)
);

-- 다시보기
create table public.replays (
  id               bigint generated by default as identity primary key,
  session_date_id  bigint not null references public.session_dates (id) on delete cascade,
  video_url        text not null,
  published_at     timestamptz not null default now()
);
create index replays_session_date_id_idx on public.replays (session_date_id);

-- 수강증 OCR 검증 로그 (enrollment_orders 가 참조하므로 먼저 생성)
create table public.enrollment_verifications (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references public.profiles (id) on delete cascade,
  file_path        text not null,                   -- storage: receipts/{user_id}/...
  ocr_raw          jsonb,
  parsed           jsonb,                           -- {name, course, teacher, time, tuition, period, receipt_no}
  candidates       jsonb,                           -- [{section_id, score, breakdown}] 튜닝용
  matched_section  bigint references public.class_sections (id),
  confidence       numeric,
  result           text check (result in ('approved', 'rejected')),
  reject_reason    text,
  receipt_no       text,
  created_at       timestamptz not null default now()
);
create index enrollment_verifications_user_id_idx on public.enrollment_verifications (user_id);
create index enrollment_verifications_matched_section_idx on public.enrollment_verifications (matched_section);
-- 영수증 1건당 1계정 (G4)
create unique index enrollment_verifications_receipt_no_approved_key
  on public.enrollment_verifications (receipt_no)
  where result = 'approved';

-- 등록 단위. 수강증 1건 = 1건
create table public.enrollment_orders (
  id               bigint generated by default as identity primary key,
  user_id          uuid not null references public.profiles (id) on delete cascade,
  verification_id  bigint references public.enrollment_verifications (id),
  months           int not null check (months between 1 and 2),
  status           text not null default 'preliminary'
                   check (status in ('preliminary', 'active', 'expired')),
  activates_on     date not null,                   -- 첫 달 개강일
  access_until     date not null,                   -- 마지막 달 종강일 (둘째 달 반 배정 시 갱신)
  created_at       timestamptz not null default now(),
  check (access_until >= activates_on)
);
create index enrollment_orders_user_id_idx on public.enrollment_orders (user_id);
create index enrollment_orders_verification_id_idx on public.enrollment_orders (verification_id);
create index enrollment_orders_status_activates_idx on public.enrollment_orders (status, activates_on);
create index enrollment_orders_status_access_idx on public.enrollment_orders (status, access_until);

-- 월별 실제 반 배정. 주5일 학생은 MWF·TTF 두 건
create table public.enrollments (
  id                       bigint generated by default as identity primary key,
  order_id                 bigint not null references public.enrollment_orders (id) on delete cascade,
  student_id               uuid not null references public.profiles (id) on delete cascade,
  section_id               bigint references public.class_sections (id),
  status                   text not null default 'active'
                           check (status in ('active', 'pending_section', 'completed')),
  -- 2개월 등록인데 둘째 달 반이 아직 없을 때: 첫 달 반을 기준으로 다음 달 같은
  -- (course, track, time_block) 반이 개설되면 자동 배정한다
  pending_from_section_id  bigint references public.class_sections (id),
  created_at               timestamptz not null default now(),
  unique (student_id, section_id),
  check (
    (status = 'pending_section' and section_id is null and pending_from_section_id is not null)
    or (status <> 'pending_section' and section_id is not null)
  )
);
create index enrollments_order_id_idx on public.enrollments (order_id);
create index enrollments_student_id_idx on public.enrollments (student_id);
create index enrollments_section_id_idx on public.enrollments (section_id);
create index enrollments_pending_idx on public.enrollments (pending_from_section_id)
  where status = 'pending_section';

-- ─── 3. 가입 시 프로필 자동 생성 ────────────────────────────────────────────
create or replace function private.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, name, phone)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'name'), ''), ''),
    nullif(trim(new.raw_user_meta_data ->> 'phone'), '')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function private.handle_new_user();

-- ─── 4. RLS 헬퍼 ───────────────────────────────────────────────────────────
-- 현재 사용자의 권한 등급. 정책 안에서 profiles 를 재귀 조회하지 않도록 definer
create or replace function private.user_role()
returns public.user_role
language sql
stable
security definer
set search_path = ''
as $$
  select p.role from public.profiles p where p.id = (select auth.uid())
$$;

create or replace function private.is_staff()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.user_role() in ('instructor', 'admin'), false)
$$;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select coalesce(private.user_role() = 'admin', false)
$$;

-- 강사는 본인 반만, admin 은 전체
create or replace function private.can_manage_section(p_section_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.is_admin()
      or exists (
        select 1 from public.class_sections s
        where s.id = p_section_id
          and s.instructor_id = (select auth.uid())
          and private.user_role() = 'instructor'
      )
$$;

-- 콘텐츠 접근 규칙 (CLAUDE.md §3)
--   role 이 student 이상
--   AND 해당 section 에 활성 enrollment (그리고 그 주문이 active — 예비등록생 차단)
--   AND today <= section.closes_at
create or replace function private.has_section_access(p_section_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select private.user_role() in ('student', 'instructor', 'admin')
     and exists (
       select 1
       from public.enrollments e
       join public.enrollment_orders o on o.id = e.order_id
       join public.class_sections s on s.id = e.section_id
       where e.student_id = (select auth.uid())
         and e.section_id = p_section_id
         and e.status = 'active'
         and o.status = 'active'
         and private.today_kst() <= s.closes_at
     )
$$;

revoke execute on function
  private.today_kst(),
  private.user_role(),
  private.is_staff(),
  private.is_admin(),
  private.can_manage_section(bigint),
  private.has_section_access(bigint)
from public, anon;

-- ─── 5. 공개 시간표 뷰 (live_url · tuition 제외, draft 제외) ─────────────────
-- 의도적으로 security_invoker 를 켜지 않는다: 비회원도 열려 있는 반의 시간표를
-- 봐야 하므로 뷰 소유자(postgres) 권한으로 읽되, 노출 컬럼을 여기서 제한한다.
create view public.class_sections_public as
  select id, course_id, term_id, bundle_id, track, start_time, end_time, time_block,
         enrollment_opens_at, closes_at, target_sessions, instructor_id, capacity, status
  from public.class_sections
  where status <> 'draft';

-- ─── 6. Data API 노출 (grant) ───────────────────────────────────────────────
grant usage on schema public to anon, authenticated, service_role;

-- 서비스 롤 (Edge Function / 배치): 전부
grant all on all tables in schema public to service_role;
grant usage, select on all sequences in schema public to service_role;

-- 비회원: 공개 마스터 데이터만
grant select on public.terms, public.courses, public.class_sections_public to anon;

-- 로그인 회원: 아래 정책이 행을 제한한다
grant select on public.terms, public.courses, public.class_sections_public to authenticated;
grant select on public.profiles to authenticated;
grant update (name, phone, role) on public.profiles to authenticated; -- 행·컬럼 조합은 정책이 제한
grant select, insert, update, delete on public.terms, public.courses to authenticated;
grant select, insert, update, delete on public.class_sections to authenticated;
grant select, insert, update, delete on public.session_dates to authenticated;
grant select, insert, update, delete on public.replays to authenticated;
grant select, update on public.enrollment_verifications to authenticated;
grant select, update on public.enrollment_orders to authenticated;
grant select, insert, update, delete on public.enrollments to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- ─── 7. RLS ────────────────────────────────────────────────────────────────
alter table public.profiles                 enable row level security;
alter table public.terms                    enable row level security;
alter table public.courses                  enable row level security;
alter table public.class_sections           enable row level security;
alter table public.session_dates            enable row level security;
alter table public.replays                  enable row level security;
alter table public.enrollment_verifications enable row level security;
alter table public.enrollment_orders        enable row level security;
alter table public.enrollments              enable row level security;

-- profiles
--   본인: 조회 + 전화번호만 수정 (name 은 수강증 대조 키, role 은 권한이라 잠근다)
--   스태프: 전체 조회. admin: 전체 수정
create policy "profiles: 본인 조회" on public.profiles
  for select to authenticated
  using ((select auth.uid()) = id);
create policy "profiles: 스태프 전체 조회" on public.profiles
  for select to authenticated
  using ((select private.is_staff()));
create policy "profiles: 본인 수정" on public.profiles
  for update to authenticated
  using ((select auth.uid()) = id)
  with check (
    (select auth.uid()) = id
    and role = (select private.user_role())
    and name = (select p.name from public.profiles p where p.id = (select auth.uid()))
  );
create policy "profiles: admin 수정" on public.profiles
  for update to authenticated
  using ((select private.is_admin()))
  with check ((select private.is_admin()));

-- terms / courses: 공개 읽기, 스태프 쓰기
create policy "terms: 공개 조회" on public.terms
  for select to anon, authenticated using (true);
create policy "terms: 스태프 쓰기" on public.terms
  for all to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

create policy "courses: 공개 조회" on public.courses
  for select to anon, authenticated using (true);
create policy "courses: 스태프 쓰기" on public.courses
  for all to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

-- class_sections: 수강생은 접근 가능한 반만(live_url 포함), 스태프는 전체
create policy "class_sections: 수강생 조회" on public.class_sections
  for select to authenticated
  using ((select private.has_section_access(id)));
create policy "class_sections: 스태프 조회" on public.class_sections
  for select to authenticated
  using ((select private.is_staff()));
create policy "class_sections: 강사 개설" on public.class_sections
  for insert to authenticated
  with check (
    (select private.is_admin())
    or ((select private.user_role()) = 'instructor' and instructor_id = (select auth.uid()))
  );
create policy "class_sections: 담당 강사 수정" on public.class_sections
  for update to authenticated
  using ((select private.can_manage_section(id)))
  with check (
    (select private.is_admin())
    or ((select private.user_role()) = 'instructor' and instructor_id = (select auth.uid()))
  );
create policy "class_sections: 담당 강사 삭제" on public.class_sections
  for delete to authenticated
  using ((select private.can_manage_section(id)));

-- session_dates
create policy "session_dates: 수강생 조회" on public.session_dates
  for select to authenticated
  using ((select private.has_section_access(section_id)));
create policy "session_dates: 스태프 조회" on public.session_dates
  for select to authenticated
  using ((select private.is_staff()));
create policy "session_dates: 담당 강사 편성" on public.session_dates
  for insert to authenticated
  with check ((select private.can_manage_section(section_id)));
create policy "session_dates: 담당 강사 수정" on public.session_dates
  for update to authenticated
  using ((select private.can_manage_section(section_id)))
  with check ((select private.can_manage_section(section_id)));
create policy "session_dates: 담당 강사 삭제" on public.session_dates
  for delete to authenticated
  using ((select private.can_manage_section(section_id)));

-- replays: 종강일까지 수강생 시청 (has_section_access 가 closes_at 검사)
create policy "replays: 수강생 시청" on public.replays
  for select to authenticated
  using (
    exists (
      select 1 from public.session_dates sd
      where sd.id = session_date_id
        and (select private.has_section_access(sd.section_id))
    )
  );
create policy "replays: 스태프 조회" on public.replays
  for select to authenticated
  using ((select private.is_staff()));
create policy "replays: 담당 강사 등록" on public.replays
  for insert to authenticated
  with check (
    exists (
      select 1 from public.session_dates sd
      where sd.id = session_date_id
        and (select private.can_manage_section(sd.section_id))
    )
  );
create policy "replays: 담당 강사 수정" on public.replays
  for update to authenticated
  using (
    exists (
      select 1 from public.session_dates sd
      where sd.id = session_date_id
        and (select private.can_manage_section(sd.section_id))
    )
  )
  with check (
    exists (
      select 1 from public.session_dates sd
      where sd.id = session_date_id
        and (select private.can_manage_section(sd.section_id))
    )
  );
create policy "replays: 담당 강사 삭제" on public.replays
  for delete to authenticated
  using (
    exists (
      select 1 from public.session_dates sd
      where sd.id = session_date_id
        and (select private.can_manage_section(sd.section_id))
    )
  );

-- enrollment_verifications: 생성은 Edge Function(service_role)만. 본인 열람, 스태프 정정
create policy "verifications: 본인 조회" on public.enrollment_verifications
  for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "verifications: 스태프 조회" on public.enrollment_verifications
  for select to authenticated
  using ((select private.is_staff()));
create policy "verifications: 스태프 정정" on public.enrollment_verifications
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

-- enrollment_orders: 생성은 Edge Function(service_role)만
create policy "orders: 본인 조회" on public.enrollment_orders
  for select to authenticated
  using ((select auth.uid()) = user_id);
create policy "orders: 스태프 조회" on public.enrollment_orders
  for select to authenticated
  using ((select private.is_staff()));
create policy "orders: 스태프 수정" on public.enrollment_orders
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

-- enrollments: 본인 조회(예비등록생 포함), 스태프 전체 관리(오배정 정정)
create policy "enrollments: 본인 조회" on public.enrollments
  for select to authenticated
  using ((select auth.uid()) = student_id);
create policy "enrollments: 스태프 관리" on public.enrollments
  for all to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

-- ─── 8. 수강증 저장소 (private bucket) ──────────────────────────────────────
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'receipts', 'receipts', false,
  10 * 1024 * 1024,
  array['image/jpeg', 'image/png', 'image/webp', 'application/pdf']
)
on conflict (id) do nothing;

-- 경로 규칙: receipts/{auth.uid()}/{filename}
create policy "receipts: 본인 폴더 업로드" on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'receipts'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "receipts: 본인 파일 조회" on storage.objects
  for select to authenticated
  using (
    bucket_id = 'receipts'
    and (storage.foldername(name))[1] = (select auth.uid())::text
  );
create policy "receipts: 스태프 조회" on storage.objects
  for select to authenticated
  using (bucket_id = 'receipts' and (select private.is_staff()));
-- 삭제(인증 후 자동 삭제)는 service_role 이 수행. 보관 기간은 미확정 6.
