-- ============================================================================
-- 특강 신청 (2026-09-16 Alan 요청)
--
--  * 특강마다 신청을 받을 수 있다 — 정원(capacity) · 신청 시작(signup_opens_at).
--    신청 받는 기간: signup_opens_at 부터 특강 당일까지, 정원이 차기 전까지.
--    신청 자격은 스터디와 같다 — 그 달 반에 배정된 수강생 (private.is_term_enrollee, 예비등록생 포함).
--    신청은 즉시 확정(스태프 승인 없음)이고, 신청 받는 중에는 본인이 취소할 수 있다.
--
--  * 특강을 id 로 유지한다. 지금까지 save_term_schedule 은 그 달 특강을 전부 지우고 다시 넣었는데,
--    신청자·정원이 붙으면 저장할 때마다 날아가거나 FK 에 막힌다.
--    → 특강을 "있으면 수정, 없으면 추가, 목록에서 빠지면 삭제" 로 바꾼다.
--      신청자가 있는 특강을 빼려고 하면 저장 전체를 거부한다 (다시보기가 붙은 회차와 같은 방식).
-- ============================================================================

-- ─── 1. 특강에 신청 칸 ─────────────────────────────────────────────────────
alter table public.special_lectures
  add column signup          boolean not null default false,
  add column capacity        int,
  add column signup_opens_at timestamptz,
  add column applied_count   int not null default 0,
  add constraint special_lectures_capacity_check check (capacity is null or capacity between 1 and 1000),
  add constraint special_lectures_applied_count_check check (applied_count >= 0),
  -- 신청을 받지 않는 특강에는 정원·신청 시작이 의미가 없다
  add constraint special_lectures_signup_fields_check
    check (signup or (capacity is null and signup_opens_at is null));

comment on column public.special_lectures.signup is '신청을 받는 특강인가. false 면 달력·시간표에 보이기만 한다';
comment on column public.special_lectures.capacity is '정원. null 이면 인원 제한 없음';
comment on column public.special_lectures.signup_opens_at is '신청 시작 일시. null 이면 바로 신청할 수 있다. 마감은 특강 당일(KST)';
comment on column public.special_lectures.applied_count is '신청 인원. lecture_signups 트리거가 유지한다 (직접 수정 불가)';

-- ─── 2. 신청 ───────────────────────────────────────────────────────────────
create table public.lecture_signups (
  id          bigint generated by default as identity primary key,
  lecture_id  bigint not null references public.special_lectures (id),  -- 신청자가 있는 특강은 삭제 불가
  user_id     uuid not null references public.profiles (id) on delete cascade,
  created_at  timestamptz not null default now(),
  unique (lecture_id, user_id)
);
create index lecture_signups_user_id_idx on public.lecture_signups (user_id);
comment on table public.lecture_signups is '특강 신청. 한 특강에 한 사람 1건';

-- 정원은 트리거가 지킨다. applied_count 를 조건부로 올려서 마지막 한 자리에 동시에 신청해도 넘지 않는다
create or replace function private.lecture_signups_sync()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    update public.special_lectures
    set applied_count = greatest(applied_count - 1, 0)
    where id = old.lecture_id;
    return old;
  end if;

  update public.special_lectures
  set applied_count = applied_count + 1
  where id = new.lecture_id
    and (capacity is null or applied_count < capacity);
  if not found then
    raise exception 'lecture_full' using errcode = 'P0001', detail = '이 특강은 정원이 찼습니다.';
  end if;
  return new;
end;
$$;

revoke execute on function private.lecture_signups_sync() from public, anon, authenticated;

create trigger lecture_signups_sync
  after insert or delete on public.lecture_signups
  for each row execute function private.lecture_signups_sync();

-- ─── 3. grant + RLS ────────────────────────────────────────────────────────
grant all on public.lecture_signups to service_role;
grant select, delete on public.lecture_signups to authenticated;
grant insert (lecture_id, user_id) on public.lecture_signups to authenticated;

-- save_term_schedule 은 security invoker 라 스태프 권한으로 특강을 고친다. applied_count 는 트리거만 건드린다.
-- 지금까지는 특강을 전부 지우고 다시 넣어서 update 정책이 없었다 — id 로 유지하려면 반드시 있어야 한다
grant update (date, lecturer_id, content, kinds, signup, capacity, signup_opens_at)
  on public.special_lectures to authenticated;

create policy "special_lectures: 스태프 수정" on public.special_lectures
  for update to authenticated
  using ((select private.is_staff())) with check ((select private.is_staff()));

alter table public.lecture_signups enable row level security;

-- 신청 받는 중인가 — 신청·취소 판정에 같은 규칙을 쓴다
create or replace function private.lecture_signup_open(p_lecture_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.special_lectures l
    where l.id = p_lecture_id
      and l.signup
      and (l.signup_opens_at is null or l.signup_opens_at <= now())
      and private.today_kst() <= l.date
      and private.is_term_enrollee(l.term_id)
  )
$$;
grant execute on function private.lecture_signup_open(bigint) to authenticated, service_role;

create policy "lecture_signups: 본인·스태프 조회" on public.lecture_signups
  for select to authenticated
  using ((select auth.uid()) = user_id or (select private.is_staff()));

create policy "lecture_signups: 수강생 신청" on public.lecture_signups
  for insert to authenticated
  with check ((select auth.uid()) = user_id and (select private.lecture_signup_open(lecture_signups.lecture_id)));

create policy "lecture_signups: 본인 취소·스태프 정리" on public.lecture_signups
  for delete to authenticated
  using (
    (select private.is_staff())
    or ((select auth.uid()) = user_id and (select private.lecture_signup_open(lecture_signups.lecture_id)))
  );

-- 특강 종류 배열 정리 — 중복을 없애고 RC · LC · 1차 · 2차 순서로
create or replace function private.lecture_kinds(p jsonb)
returns text[]
language sql
immutable
set search_path = ''
as $$
  select coalesce(array_agg(x.k order by array_position(array['rc', 'lc', 'mock1', 'mock2'], x.k)), '{}')
  from (select distinct jsonb_array_elements_text(coalesce(p, '[]'::jsonb)) as k) as x
$$;
grant execute on function private.lecture_kinds(jsonb) to authenticated, service_role;

-- ─── 4. 저장: 특강을 id 로 유지한다 ────────────────────────────────────────
-- p_lectures 항목: {"id": 12|null, "date", "lecturer_id", "kinds":[…], "content",
--                   "signup": bool, "capacity": int|null, "signup_opens_at": "…"|null}
--   id 가 있으면 그 특강을 수정하고, 없으면 새로 만든다. 목록에서 빠진 특강은 지운다.
--   신청자가 있는 특강을 빼려고 하면 저장 전체를 거부한다 (lecture_signup_block).
create or replace function public.save_term_schedule(
  p_year      int,
  p_month     int,
  p_opens     date,
  p_closes    date,
  p_mwf       date[],
  p_ttf       date[],
  p_lectures  jsonb,
  p_parts     text[] default null
)
returns jsonb
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_term_id     bigint;
  v_first       date;
  v_last        date;
  v_from        date;
  v_to          date;
  v_mwf         date[] := coalesce(p_mwf, '{}');
  v_ttf         date[] := coalesce(p_ttf, '{}');
  v_lectures    jsonb  := coalesce(p_lectures, '[]'::jsonb);
  v_parts       text[] := coalesce(p_parts, array['dates', 'mwf', 'ttf', 'lectures']);
  v_do_dates    boolean;
  v_do_mwf      boolean;
  v_do_ttf      boolean;
  v_do_lectures boolean;
  v_bad         text;
  v_sections    int;
  v_keep        bigint[];
begin
  if not (select private.is_staff()) then
    raise exception 'forbidden' using errcode = '42501';
  end if;
  if p_year is null or p_month is null or p_year not between 2020 and 2100 or p_month not between 1 and 12 then
    raise exception 'invalid_term' using errcode = '22023';
  end if;

  -- ─── 저장할 항목 고르기 ──────────────────────────────────────────────────
  if 'all' = any(v_parts) then
    v_parts := array['dates', 'mwf', 'ttf', 'lectures'];
  end if;
  if exists (select 1 from unnest(v_parts) as p where p is null or p not in ('dates', 'mwf', 'ttf', 'lectures')) then
    raise exception 'invalid_parts' using errcode = '22023';
  end if;
  v_do_dates    := 'dates'    = any(v_parts);
  v_do_mwf      := 'mwf'      = any(v_parts);
  v_do_ttf      := 'ttf'      = any(v_parts);
  v_do_lectures := 'lectures' = any(v_parts);
  if not (v_do_dates or v_do_mwf or v_do_ttf or v_do_lectures) then
    raise exception 'invalid_parts' using errcode = '22023';
  end if;

  if v_do_dates then
    if p_opens is null or p_closes is null then
      raise exception 'dates_required' using errcode = '22023';
    end if;
    if p_closes < p_opens then
      raise exception 'closes_before_opens' using errcode = '22023';
    end if;
  end if;

  -- 수업일·특강을 찍을 수 있는 범위: 지난달 1일 ~ 다음달 말일
  v_first := make_date(p_year, p_month, 1);
  v_last  := (v_first + interval '1 month')::date - 1;
  v_from  := (v_first - interval '1 month')::date;
  v_to    := (v_first + interval '2 months')::date - 1;

  -- ─── 수업일 ──────────────────────────────────────────────────────────────
  if v_do_mwf and exists (select 1 from unnest(v_mwf) as d where d is null or d < v_from or d > v_to) then
    raise exception 'class_date_out_of_range' using errcode = '22023';
  end if;
  if v_do_ttf and exists (select 1 from unnest(v_ttf) as d where d is null or d < v_from or d > v_to) then
    raise exception 'class_date_out_of_range' using errcode = '22023';
  end if;
  if v_do_mwf and v_do_ttf then
    select string_agg(to_char(x.d, 'YYYY-MM-DD'), ',' order by x.d) into v_bad
    from (select unnest(v_mwf) as d intersect select unnest(v_ttf)) as x;
    if v_bad is not null then
      raise exception 'track_overlap' using errcode = '22023', detail = v_bad;
    end if;
  end if;

  -- ─── 특강 검증 ───────────────────────────────────────────────────────────
  if v_do_lectures then
    if jsonb_typeof(v_lectures) <> 'array' or jsonb_array_length(v_lectures) > 100 then
      raise exception 'invalid_lectures' using errcode = '22023';
    end if;
    if exists (
      select 1
      from jsonb_array_elements(v_lectures) as e
      where jsonb_typeof(e) <> 'object'
         or e ->> 'date' is null
         or e ->> 'lecturer_id' is null
         or (e ->> 'date')::date not between v_from and v_to
         or (e -> 'kinds' is not null and jsonb_typeof(e -> 'kinds') <> 'array')
         or coalesce(jsonb_array_length(e -> 'kinds'), 0) > 4
         or exists (
              select 1 from jsonb_array_elements_text(coalesce(e -> 'kinds', '[]'::jsonb)) as k
              where k not in ('rc', 'lc', 'mock1', 'mock2')
            )
         or (coalesce(jsonb_array_length(e -> 'kinds'), 0) = 0
             and char_length(btrim(coalesce(e ->> 'content', ''))) = 0)
         or char_length(btrim(coalesce(e ->> 'content', ''))) > 100
         or ((e ->> 'capacity') is not null and (e ->> 'capacity')::int not between 1 and 1000)
    ) then
      raise exception 'invalid_lectures' using errcode = '22023';
    end if;
  end if;

  -- ─── 기수 행 ─────────────────────────────────────────────────────────────
  insert into public.terms (year, month) values (p_year, p_month)
  on conflict (year, month) do nothing;
  select t.id into v_term_id from public.terms t where t.year = p_year and t.month = p_month;

  -- ─── 월(기수) 구분: 같은 날짜를 다른 기수가 이미 수업일로 쓰면 거부 ─────
  select string_agg(distinct to_char(d.date, 'YYYY-MM-DD') || '@' || t.year || '-' || lpad(t.month::text, 2, '0'), ',')
    into v_bad
  from public.term_class_dates d
  join public.terms t on t.id = d.term_id
  where d.term_id <> v_term_id
    and d.date = any(
      case
        when v_do_mwf and v_do_ttf then v_mwf || v_ttf
        when v_do_mwf then v_mwf
        when v_do_ttf then v_ttf
        else '{}'::date[]
      end
    );
  if v_bad is not null then
    raise exception 'date_in_other_term' using errcode = '22023', detail = v_bad;
  end if;

  if v_do_dates then
    update public.terms
    set enrollment_opens_at = p_opens,
        closes_at = p_closes
    where id = v_term_id;
  end if;

  -- ─── 수업일: 저장하는 트랙만 갈아 끼운다 ────────────────────────────────
  if v_do_mwf then
    delete from public.term_class_dates
    where term_id = v_term_id and (track = 'mwf' or date = any(v_mwf));
  end if;
  if v_do_ttf then
    delete from public.term_class_dates
    where term_id = v_term_id and (track = 'ttf' or date = any(v_ttf));
  end if;
  if v_do_mwf then
    insert into public.term_class_dates (term_id, date, track)
    select v_term_id, m.d, 'mwf' from (select distinct unnest(v_mwf) as d) as m;
  end if;
  if v_do_ttf then
    insert into public.term_class_dates (term_id, date, track)
    select v_term_id, t.d, 'ttf' from (select distinct unnest(v_ttf) as d) as t;
  end if;

  -- ─── 특강: id 로 유지 (수정 / 추가 / 빠진 것 삭제) ──────────────────────
  if v_do_lectures then
    select coalesce(array_agg((e ->> 'id')::bigint), '{}')
      into v_keep
    from jsonb_array_elements(v_lectures) as e
    where e ->> 'id' is not null;

    -- 넘겨받은 id 가 이 기수 특강이 맞는지 (남의 기수 특강을 건드리지 못하게)
    if exists (
      select 1 from unnest(v_keep) as k
      where not exists (select 1 from public.special_lectures l where l.id = k and l.term_id = v_term_id)
    ) then
      raise exception 'invalid_lectures' using errcode = '22023';
    end if;

    -- 빠지는 특강에 신청자가 있으면 저장 전체를 되돌린다
    select string_agg(to_char(l.date, 'YYYY-MM-DD'), ',' order by l.date)
      into v_bad
    from public.special_lectures l
    where l.term_id = v_term_id
      and not (l.id = any(v_keep))
      and exists (select 1 from public.lecture_signups g where g.lecture_id = l.id);
    if v_bad is not null then
      raise exception 'lecture_signup_block' using errcode = 'P0001', detail = v_bad;
    end if;

    delete from public.special_lectures l
    where l.term_id = v_term_id and not (l.id = any(v_keep));

    -- 정원을 이미 신청한 인원보다 적게 줄일 수 없다
    select string_agg(to_char(l.date, 'YYYY-MM-DD'), ',' order by l.date)
      into v_bad
    from jsonb_array_elements(v_lectures) as e
    join public.special_lectures l on l.id = (e ->> 'id')::bigint
    where e ->> 'id' is not null
      and (e ->> 'capacity') is not null
      and (e ->> 'capacity')::int < l.applied_count;
    if v_bad is not null then
      raise exception 'lecture_capacity_below_applied' using errcode = '22023', detail = v_bad;
    end if;

    -- 수정. 신청 설정(signup·capacity·signup_opens_at)은 **넘어온 키만** 바꾼다 —
    -- 반 편성 달력은 신청 설정을 다루지 않으므로 그냥 두면 그대로 남아야 한다
    update public.special_lectures l
    set date            = (e.v ->> 'date')::date,
        lecturer_id     = (e.v ->> 'lecturer_id')::bigint,
        content         = nullif(btrim(coalesce(e.v ->> 'content', '')), ''),
        kinds           = private.lecture_kinds(e.v -> 'kinds'),
        signup          = case when e.v ? 'signup' then coalesce((e.v ->> 'signup')::boolean, false) else l.signup end,
        capacity        = case when e.v ? 'capacity' then (e.v ->> 'capacity')::int else l.capacity end,
        signup_opens_at = case when e.v ? 'signup_opens_at' then (e.v ->> 'signup_opens_at')::timestamptz else l.signup_opens_at end
    from jsonb_array_elements(v_lectures) as e(v)
    where e.v ->> 'id' is not null and l.id = (e.v ->> 'id')::bigint and l.term_id = v_term_id;

    -- 추가
    insert into public.special_lectures (term_id, date, lecturer_id, content, kinds, signup, capacity, signup_opens_at)
    select
      v_term_id,
      (e.v ->> 'date')::date,
      (e.v ->> 'lecturer_id')::bigint,
      nullif(btrim(coalesce(e.v ->> 'content', '')), ''),
      private.lecture_kinds(e.v -> 'kinds'),
      coalesce((e.v ->> 'signup')::boolean, false),
      (e.v ->> 'capacity')::int,
      (e.v ->> 'signup_opens_at')::timestamptz
    from jsonb_array_elements(v_lectures) with ordinality as e(v, ord)
    where e.v ->> 'id' is null
    order by e.ord;
  end if;

  v_sections := private.sync_term_sections(v_term_id);

  return jsonb_build_object(
    'term_id',  v_term_id,
    'parts',    to_jsonb(v_parts),
    'mwf',      (select count(*) from public.term_class_dates where term_id = v_term_id and track = 'mwf'),
    'ttf',      (select count(*) from public.term_class_dates where term_id = v_term_id and track = 'ttf'),
    'lectures', (select count(*) from public.special_lectures where term_id = v_term_id),
    'sections', v_sections
  );
end;
$$;

comment on function public.save_term_schedule(int, int, date, date, date[], date[], jsonb, text[]) is
  '반 편성 달력 저장. p_parts 로 항목만 고른다. 수업일·특강은 그 달 ±1개월, 수업일은 다른 기수와 겹칠 수 없다. 특강은 id 로 유지되고(신청자가 있으면 삭제 거부) kinds·신청 설정(signup·capacity·signup_opens_at)을 함께 받는다';

revoke all on function public.save_term_schedule(int, int, date, date, date[], date[], jsonb, text[]) from public, anon;
grant execute on function public.save_term_schedule(int, int, date, date, date[], date[], jsonb, text[]) to authenticated, service_role;
